loaded_h_0(function(_){var window=this;
_.t("IoGlCf");
_.YKc=new _.Ke(_.f0a);
_.u();
_.sz=_.x("C8HsP",[_.f0a]);
_.t("C8HsP");
var ZKc;_.tz=new Set;ZKc=function(a,b){b.Da()||(a=_.Cf(a.getRoot().el(),c=>c instanceof Element&&_.Ve(c,"ved"),!0))&&(a=_.Te(a,"ved"))&&b.Aa(a)};_.uz=function(a,b){let c;a.getRoot().el().setAttribute("data-vhid",(c=b==null?void 0:b.VV())!=null?c:"");ZKc(a,b);a.Ha.resolve(b);a.PPc(b)};_.vz=function(a,b,c){ZKc(a,c);a.Aa.set(b,c);a.Da=!0};
_.$Kc=function(a,b,c,d){if(b.event){var e;let k;(k=(e=b.event).preventDefault)==null||k.call(e);let l,n;(n=(l=b.event).stopPropagation)==null||n.call(l)}c&&ZKc(a,c);var f;d=d?(f=_.Te(d,"ved"))!=null?f:void 0:void 0;f=a.Ca(b);let g,h;e=((g=b.qb)==null?0:g.el())?_.Ve((h=b.qb)==null?void 0:h.el(),"hsr"):!1;a.trigger("aevozb",{iKe:c,interactionVed:d,interactionContext:f,gha:e})};
_.wz=class extends _.Wr{static Sa(){return{service:{QIa:_.YKc}}}constructor(a){super(a.Oa);this.Aa=new Map;this.Da=!1;this.Ha=_.qe();this.QIa=a.service.QIa;this.trigger("k7WJpc")}Pa(a){a.data.element?_.vz(this,a.data.element,a.data.zo):_.uz(this,a.data.zo)}async rz(){return await this.Ha.promise}Oc(a){if(this.Da){let b=a.targetElement.el();const c=this.getRoot().el();for(;b&&b!==c;){if(this.Aa.has(b))return _.$Kc(this,a,this.Aa.get(b),b),!1;b=b.parentElement}c&&this.Aa.has(c)?_.$Kc(this,a,this.Aa.get(c),
c):_.$Kc(this,a)}else _.$Kc(this,a);return!1}Ca(a){return(a=a.qb.el())?Number(_.Te(a,"ictx"))||void 0:void 0}PPc(a){let b;(a=(b=a.Ba())==null?void 0:b.getViewerType())&&_.tz.has(a)&&this.QIa.PPc(a)}async WOa(a){this.trigger("vcOT6c",a)}Ta(){return!1}};_.wz.prototype.$wa$M5Scjd=function(){return this.Ta};_.wz.prototype.$wa$zYAnae=function(){return this.Ca};_.wz.prototype.$wa$h5M12e=function(){return this.Oc};_.wz.prototype.$wa$mKCalb=function(){return this.rz};_.wz.prototype.$wa$kNqZ1c=function(){return this.Pa};
_.Yr(_.sz,_.wz);
_.tz.add(10);_.tz.add(15);_.tz.add(16);_.tz.add(18);_.tz.add(19);_.tz.add(25);_.tz.add(36);_.tz.add(21);_.tz.add(22);_.tz.add(23);_.tz.add(24);_.tz.add(26);_.tz.add(27);_.tz.add(28);_.tz.add(29);_.tz.add(31);_.tz.add(40);_.tz.add(32);_.tz.add(33);_.tz.add(35);
_.u();
_.QLc=_.x("gOTY1",[_.nxa,_.f0a]);
_.Kz=class extends _.m{constructor(a){super(a)}};_.Kz.prototype.ob="PFrTzf";
_.jLc=function(a,b){return _.Vh(a,1,_.zz,b)};_.kLc=function(a){return _.ei(a,_.su,1,_.hLc)};_.Gz=function(a,b){return _.ji(a,1,_.hLc,b)};_.Hz=function(a,b){return _.Uf(a,3,b)};_.lLc=function(a,b){return _.Uf(a,7,b)};_.mLc=_.Mb(_.Fz);
_.t("gOTY1");
var RLc=function(a){const b=a.getRoot().el();a=[...b.querySelectorAll('[data-viewer-entrypoint]:not([data-nv="1"])')];return a.length===0?a:a.filter(c=>{for(c=c.parentElement;c!==null&&c!==b;){if(c.hasAttribute("data-viewer-group"))return!1;c=c.parentElement}return!0})},TLc=async function(a,b,c=null,d=null){try{const e=_.y(await _.y(Promise.all(b.map(k=>SLc(a,k))))),f=new Set,g=e.filter(k=>f.has(k.VV())?!1:(f.add(k.VV()),!0)),h=_.pLc(_.nLc(new _.Iz,g),a.streamId);a.Yjc&&h.setQuery(a.Yjc);if(c&&d){const k=
b.indexOf(c);k>=0&&_.Wh(h,1,_.Fz,k,d)}return h}finally{_.y()}},SLc=function(a,b){if(a.Ca.has(b))return a.Ca.get(b);const c=ULc(a,b);a.Ca.set(b,c);return c},ULc=async function(a,b){try{if(_.LLc)try{return _.y(await _.y(a.Bl.resolve(b,_.Fz)))}catch(c){_.y()}return _.y(await _.y(a.xc(b,_.wo))).rz()}finally{_.y()}},VLc=class extends _.Wr{static Sa(){return{service:{Bl:_.YXa,QIa:_.YKc},Ef:{aoa:_.Kz}}}constructor(a){super(a.Oa);this.Ca=new Map;this.oa=[];this.Ba=this.Aa=null;this.Da=Promise.resolve();this.Bl=
a.service.Bl;this.QIa=a.service.QIa;let b,c;this.streamId=(c=(b=_.ll(this.getData("id")))!=null?b:_.ll(this.getData("vssid")))!=null?c:"global";this.Yjc=_.ll(this.getData("q"));this.aoa=a.Ef.aoa;_.LLc||this.zn(this.initialize(),_.ao)}async initialize(){try{const a=RLc(this);_.y(await _.y(this.registerStream(a)))}finally{_.y()}}async Lwb(a){try{const c=a.targetElement.el();var b;const d=(b=a.data.iKe)!=null?b:null;b=d?c:null;let e=void 0;if(_.LLc){const h=RLc(this);e=_.y(await _.y(TLc(this,h,b,d)))}else this.Aa===
b&&this.Ba===d||_.y(await _.y(this.registerStream(this.oa,b,d)));const f=d!=null?d:_.y(await _.y(SLc(this,c)));let g;_.y(await _.y(this.QIa.navigateToView({streamId:this.streamId,historyId:f.VV(),resultElement:c,xJb:_.uua(a)+_.ig,jWc:_.si(f,5),interactionVed:a.data.interactionVed,interactionContext:a.data.interactionContext,replace:!!a.data.gha,aoa:(g=this.aoa)!=null?g:void 0,stream:e})))}finally{_.y()}}bIc(a){this.QIa.WOa(a.data)}async Ea(a){try{const b=a.targetElement.el();if(!_.LLc&&!this.oa.includes(b)){const c=
RLc(this);_.y(await _.y(this.registerStream(c,this.Aa,this.Ba)))}}finally{_.y()}}async Ha(){try{if(!_.LLc){const a=RLc(this);_.y(await _.y(this.registerStream(a,this.Aa,this.Ba)))}return!0}finally{_.y()}}async registerStream(a,b=null,c=null){try{const d=this.oa;this.oa=a;this.Aa=b;this.Ba=c;const e=this.Da,f=new _.hh;this.Da=f.promise;_.y(await _.y(e));const g=_.y(await _.y(TLc(this,a,b,c)));a.length>0&&d.length===0?_.y(await _.y(this.QIa.registerStream(this,g))):_.y(await _.y(this.QIa.YWe(this,g)));
f.resolve()}finally{_.y()}}Ub(){_.LLc||this.QIa.zpc(this,this.streamId)}};VLc.prototype.$wa$k4Iseb=function(){return this.Ub};VLc.prototype.$wa$sCDZjb=function(){return this.Ha};VLc.prototype.$wa$beCLof=function(){return this.Ea};VLc.prototype.$wa$C6KsF=function(){return this.bIc};VLc.prototype.$wa$T2P31d=function(){return this.Lwb};_.Yr(_.QLc,VLc);
_.u();
_.kpe=function(a){return _.Ig(a,1,2)};_.lpe=function(a){return _.Ig(a,2,2)};_.mpe=function(a,b){return _.Ig(a,3,b)};
_.Voe=function(a,b){return _.Uf(a,9,b)};_.Woe=function(a,b){return _.Uf(a,10,b)};_.Xoe=function(a,b){return _.Uf(a,12,b)};_.Yoe=function(a,b){return _.oh(a,2,b)};_.Zoe=function(a,b){return _.oh(a,3,b)};_.$oe=function(a,b){return _.Ig(a,1,b)};_.ape=function(a,b){return _.Uf(a,2,b)};var bpe=[0,_.E,_.D];var cpe=[0,_.E,_.rk,_.C,_.E];var dpe=class extends _.m{constructor(a){super(a)}};dpe.prototype.ob="IV0Wqf";var epe=[0,_.E,-1];_.fpe=function(a,b){return _.Uf(a,3,b)};_.gpe=function(a,b){return _.Uf(a,4,b)};_.hpe=function(a,b){return _.Uf(a,13,b)};_.ipe=function(a,b){return _.Uf(a,18,b)};
_.jpe=class extends _.m{constructor(a){super(a,37)}yF(){return _.A(this,3)}T5(){return _.si(this,3)}rB(){return _.A(this,4)}psa(){return _.si(this,4)}Xe(){return _.A(this,5)}Eu(){return _.zj(this,5)}Bv(){return _.A(this,11)}EF(){return _.A(this,13)}oEa(){return _.si(this,13)}gfb(){return _.A(this,18)}zk(){return _.A(this,31)}Sfb(){return _.p(this,dpe,32)}};_.jpe.prototype.ob="onFC6b";_.BG=_.Cb(2003,_.pG,_.jpe);_.qle[2003]=[-37,{},_.E,-4,_.D,1,_.E,1,_.D,_.E,_.D,_.E,4,_.E,cpe,1,bpe,1,_.D,1,_.D,2,_.D,_.E,1,_.E,epe,1,_.E,_.so,_.D];
var Toe=class extends _.m{constructor(a){super(a)}};Toe.prototype.ob="LMXOyf";_.Uoe=_.Cb(2009,_.pG,Toe);_.qle[2009]=[0,_.D];
_.t("cNgdQc");
var ppe,ope,npe;
_.qpe=function(a){if(a){var b=a.getImage(),c,d=b==null?void 0:(c=b.getExtension(_.BG))==null?void 0:c.yF(),e;d&&((e=_.Zk(d))==null?0:e.match(/\.gstatic\.com$/))&&_.rEa(d)==="/licensed-image"&&(b==null||_.$oe(b,18));switch(b==null?void 0:_.Xi(b,1)){case 16:c=a.Ba;d=new _.sle;d=_.Kg(d,5,!0);d=_.Ig(d,6,2);c=c.call(a,d);d=c.Aa;e=npe(ope(ppe(_.mpe(_.lpe(new _.rle),2))));e=_.Kg(e,5,!0);d.call(c,e);break;case 9:case 19:a.Aa(npe(ope(ppe(_.mpe(_.lpe(new _.rle),2)))));break;case 18:a.Aa(_.lpe(_.kpe(ppe(new _.rle))));break;
case 20:a.Aa(_.kpe(_.lpe(new _.rle)));break;case 23:a.Aa(npe(ope(ppe(_.mpe(_.kpe(_.lpe(new _.rle)),2)))))}var f,g;c=(g=b==null?void 0:_.z(b,9))!=null?g:!1;g=(b==null?void 0:_.wi(b,1))===18;!c&&!g&&(b==null?void 0:(f=b.Qe(_.Uoe))==null?void 0:_.Lg(f,1))!==!0||_.mpe(a.Ca(),2)}};_.rpe=function(a){a&&(a.oa(_.BG,a.Qe(_.BG)||new _.jpe),a=a.getExtension(_.BG),a.EF()||_.hpe(a,a.gfb()||_.Zk(a.yF()||"")))};ppe=function(a){return _.Ig(a,4,2)};ope=function(a){return _.Ig(a,7,2)};
npe=function(a){return _.Ig(a,8,2)};
_.u();
_.t("K02r3e");

_.u();
_.l0q=_.x("qKrDxc",[_.lr,_.Xq,_.hr,_.Pk,_.sz]);
_.rG=class extends _.m{constructor(a){super(a,2)}xu(){return _.bg(this,_.pG,1,_.cg())}};_.rG.prototype.ob="U9CFPc";_.Fle=[-2,{},_.F,_.Cle];
_.Gle=function(a,b){return _.Uf(a,1,b)};_.Hle=function(a,b){return _.Bb(a,_.pG,2,b)};_.Ile=function(a){return _.p(a,_.rle,15)};_.Jle=_.Mb(_.pG);_.Kle=_.Mb(_.qG);new _.ih(_.pG);_.So.XZxcdf=function(a){return _.To(_.Uo(_.ple(a)))};new _.ih(_.rG);_.So.U9CFPc=_.Ro;_.Fq(_.rG,_.pG,function(a){return a.xu()});_.sG=_.Cb(444383007,_.xz,_.qG);_.yz[444383007]=_.Ele;var Lle=new _.ih(_.qG);Lle.Wa=new _.ih(_.ule);Lle.wb=_.sG;_.So.j0Opre=function(a){return _.To(_.Uo(a.Df()))};_.Fq(_.qG,_.pG,function(a){a=a.getImage();return a!=null?[a]:[]});_.Fq(_.qG,_.ule,function(a){a=a.HDa();return a!=null?[a]:[]});_.So.IRVcEb=function(a){return _.To(_.Uo(a.Df()))};
var Uqe;
_.Vqe=function(a,b,c,d,e){var f=(a==null?void 0:a.Ha())||"";if(!f){var g,h,k;if(a=(h=(g=a.Ca())==null?void 0:g.ze())==null?void 0:(k=h.Qe(_.sG))==null?void 0:k.getImage()){f=a;a=(0,_.Kle)(f)?f.getImage():f;g=(f=a.Qe(_.BG))&&_.Vf(f,2);h=f&&_.Vf(f,3);k=_.Vf(a,2);var l=a.nJ();a=l?_.mle(l):"";const n=l?_.ole(l):"";l=l?_.nle(l):"";if(!g||!h||!k)throw Error("qn");b=new Map([["q",b],["imgurl",a],["imgrefurl",h],["docid",g],["tbnid",k],["vet",1],["w",n],["h",l],["hcb","2"]]);_.z(f,10)&&b.set("itg",1);c&&
(b.set("ved",c),d&&b.set("ictx",d),e&&b.set("vet",e));f=_.jc(Uqe,b)}}return f};Uqe=(0,_.ic)`/imgres`;
_.HRc=function(a){return _.p(a,_.pu,4)};
_.t("qKrDxc");
var m0q=function(a){var b=(new _.su).Pp(7);const c=a.getId(),d=new _.zz;_.Cz(d).oa(_.sG,a);b=_.Ez(_.Hz(_.Gz(new _.Fz,b),c),d);_.qpe(a);_.rpe(a.getImage());return b};var n0q=async function(a,b,c){try{const g=_.y(await _.y(a.rz())),h=_.A(g,5);var d=a.Ca(c),e=(c=h)&&_.LUa(h)||void 0;const k=_.Vqe(g,_.Gn(new _.zn(a.Vi.getCurrentUrl()),"q")||"",c,d,e);if(k){var f=_.ac(k.toString());f&&_.Ac(b,f)}}finally{_.y()}},o0q=class extends _.wz{static Sa(){return{jsdata:{Ds:_.qG},service:{history:_.CG,navigation:_.Vz,focus:_.tw,Ec:_.Ku}}}constructor(a){super(a.Oa);this.Ea=!1;this.Ba=b=>{const c=this.getRoot();if(c.el()){var d=_.ll(this.getData("docid"));c.toggleClass("loWRed",
d!==null&&b.detail.vhid===d)}};this.oa=()=>{const b=this.getRoot();b.el()&&b.hasClass("loWRed")&&(b.removeClass("loWRed"),this.Af.hU(b,{preventScroll:!0}))};_.uz(this,m0q(a.jsdata.Ds));this.Vi=a.service.history;this.kc=a.service.navigation;this.Af=a.service.focus;this.Tb=a.service.Ec;this.logger=null;_.Fw&&(document.addEventListener("viewerUpdated",this.Ba),document.addEventListener("viewerClosed",this.oa),this.addOnDisposeCallback(()=>{document.removeEventListener("viewerUpdated",this.Ba);document.removeEventListener("viewerClosed",
this.oa)}))}Ka(a){if(this.Ea)return!0;let b=a.targetElement.el();for(let c=0;c<10&&b;c++,b=b.parentElement){let d;if(((d=b)==null?void 0:d.tagName)==="A"){n0q(this,b,a);this.Ea=!0;break}}return!0}Oc(a){this.trigger("yu1Hm");return super.Oc(a)}Na(a){this.Oc(a);return null}Ma(a){a=a.targetElement.el();if(!a)return null;var b=a.getAttribute("href");if(!b)return null;b=_.ac(b);if(!b)return null;this.kc.navigateTo(b);this.Tb.logEvent({oe:_.Bg(a)});return null}};o0q.prototype.$wa$WZxsNc=function(){return this.Ma};
o0q.prototype.$wa$Esn7Cd=function(){return this.Na};o0q.prototype.$wa$h5M12e=function(){return this.Oc};o0q.prototype.$wa$UI3Kjd=function(){return this.Ka};_.Yr(_.l0q,o0q);
_.u();
});
// Google Inc.
