loaded_h_0(function(_){var window=this;
_.XsB=_.x("VD4Qme",[]);
_.WsB=function(a){return a.replace(/_/g,"_1").replace(/,/g,"_2").replace(/:/g,"_3")};
_.Zfd=new _.BC(0,0,1);_.$fd=new _.BC(9999,11,31);
var n1c;n1c={D3b:"y",p1d:"y G",vqb:"MMM y",Gab:"MMMM y",q1d:"MM/y",cma:"MMM d",Wsc:"MMMM dd",iqb:"M/d",hqb:"MMMM d",ZGb:"MMM d, y",oqa:"EEE, MMM d",C8c:"EEE, MMM d, y",B5c:"d",duf:"MMM d, h:mm\u202fa zzzz"};_.LC=n1c;_.LC=n1c;
_.S0c=function(a,b,c,d,e,f,g){a=typeof a==="number"?Date.UTC(a,b||0,c||1,d||0,e||0,f||0,g||0):a?a.getTime():_.Ch();this.date=new Date(a)};_.Dh(_.S0c,_.EC);_.aa=_.S0c.prototype;_.aa.clone=function(){const a=new _.S0c(this.date);a.kLa=this.kLa;a.reb=this.reb;return a};_.aa.add=function(a){(a.oa||a.xI)&&_.BC.prototype.add.call(this,new _.AC(a.oa,a.xI));a=1E3*(a.tT+60*(a.minutes+60*(a.hours+24*a.PD)));this.date=new Date(this.date.getTime()+a)};_.aa.getTimezoneOffset=function(){return 0};
_.aa.getFullYear=_.EC.prototype.getUTCFullYear;_.aa.getMonth=_.EC.prototype.getUTCMonth;_.aa.getDate=_.EC.prototype.getUTCDate;_.aa.getHours=_.EC.prototype.getUTCHours;_.aa.getMinutes=_.EC.prototype.getUTCMinutes;_.aa.getSeconds=_.EC.prototype.getUTCSeconds;_.aa.getMilliseconds=_.EC.prototype.getUTCMilliseconds;_.aa.getDay=_.EC.prototype.getUTCDay;_.aa.setFullYear=_.EC.prototype.setUTCFullYear;_.aa.setMonth=_.EC.prototype.setUTCMonth;_.aa.setDate=_.EC.prototype.setUTCDate;_.aa.setHours=_.EC.prototype.setUTCHours;
_.aa.setMinutes=_.EC.prototype.setUTCMinutes;_.aa.setSeconds=_.EC.prototype.setUTCSeconds;_.aa.setMilliseconds=_.EC.prototype.setUTCMilliseconds;
var V0c;_.T0c=function(a){return((a.getDay()+6)%7-a.kLa+7)%7};_.U0c=function(a){return _.P_c(a.getFullYear(),a.getMonth())};V0c=function(a,b,c,d,e){a=new Date(a,b,c);d=d!==void 0?d:3;e=e||0;b=((a.getDay()+6)%7-e+7)%7;return a.valueOf()+((d-e+7)%7-b)*864E5};_.W0c=function(a,b){return a<b?a:b};var X0c,Y0c,$0c;X0c=function(){};
_.Z0c=function(a){if(typeof a=="number"){var b=new X0c;b.Da=a;var c=a;if(c==0)c="Etc/GMT";else{var d=["Etc/GMT",c<0?"-":"+"];c=Math.abs(c);d.push(Math.floor(c/60)%100);c%=60;c!=0&&d.push(":",_.Tk(c,2));c=d.join("")}b.Ba=c;c=a;c==0?c="UTC":(d=["UTC",c<0?"+":"-"],c=Math.abs(c),d.push(Math.floor(c/60)%100),c%=60,c!=0&&d.push(":",c),c=d.join(""));a=Y0c(a);b.Ca=[c,c];b.oa={FHf:a,a8c:a};b.Aa=[];return b}b=new X0c;b.Ba=a.id;b.Da=-a.std_offset;b.Ca=a.names;b.oa=a.names_ext;b.Aa=a.transitions;return b};
Y0c=function(a){const b=["GMT"];b.push(a<=0?"+":"-");a=Math.abs(a);b.push(_.Tk(Math.floor(a/60)%100,2),":",_.Tk(a%60,2));return b.join("")};$0c=function(a,b){b=Date.UTC(b.getUTCFullYear(),b.getUTCMonth(),b.getUTCDate(),b.getUTCHours(),b.getUTCMinutes())/36E5;let c=0;for(;c<a.Aa.length&&b>=a.Aa[c];)c+=2;return c==0?0:a.Aa[c-1]};_.a1c=function(a,b){a=a.Da-$0c(a,b);return a===-1440?0:a};X0c.prototype.R0=function(a){return this.Ca[$0c(this,a)>0?2:0]};var d1c,e1c,c1c;_.KC=function(a,b){this.Aa=[];this.oa=b||_.zC;typeof a=="number"?b1c(this,a):c1c(this,a)};d1c=[/^'(?:[^']|'')*('|$)/,/^(?:G+|y+|Y+|u+|M+|k+|S+|E+|a+|b+|B+|h+|K+|H+|c+|L+|Q+|d+|m+|s+|v+|V+|w+|z+|Z+)/,/^[^'GyYuMkSEabBhKHcLQdmsvVwzZ]+/];e1c=function(a){return a.getHours?a.getHours():0};
c1c=function(a,b){for(f1c&&(b=b.replace(/\u200f/g,""));b;){const c=b;for(let d=0;d<d1c.length;++d){const e=b.match(d1c[d]);if(e){let f=e[0];b=b.substring(f.length);d==0&&(f=="''"?f="'":(f=f.substring(1,e[1]=="'"?f.length-1:f.length),f=f.replace(/''/g,"'")));a.Aa.push({text:f,type:d});break}}if(c===b)throw Error("Ph`"+b);}};
_.KC.prototype.format=function(a,b){if(!a)throw Error("Qh");var c=b?(a.getTimezoneOffset()-_.a1c(b,a))*6E4:0;let d=c?new Date(a.getTime()+c):a;var e=d;b&&d.getTimezoneOffset()!=a.getTimezoneOffset()&&(e=(d.getTimezoneOffset()-a.getTimezoneOffset())*6E4,d=new Date(d.getTime()+e),c+=c>0?-864E5:864E5,e=new Date(a.getTime()+c));c=[];for(let f=0;f<this.Aa.length;++f){const g=this.Aa[f].text;1==this.Aa[f].type?c.push(g1c(this,g,a,d,e,b)):c.push(g)}return c.join("")};
var b1c=function(a,b){let c;if(b<4)c=a.oa.lRa[b];else if(b<8)c=a.oa.uqb[b-4];else if(b<12)c=a.oa.z5c[b-8],c=c.replace("{1}",a.oa.lRa[b-8]),c=c.replace("{0}",a.oa.uqb[b-8]);else if(b===12)c=a.oa.lRa[0].replace(/[^EMd]*yy*[^EMd]*/,"");else if(b===13)c=a.oa.lRa[2].replace(/[^EMd]*yy*[^EMd]*/,"");else{b1c(a,10);return}c1c(a,c)},i1c=function(a,b){{b=String(b);const c=a.oa||_.zC;if(c.Ytc!==void 0&&!h1c){a=[];for(let d=0;d<b.length;d++){const e=b.charCodeAt(d);a.push(48<=e&&e<=57?String.fromCharCode(c.Ytc+
e-48):b.charAt(d))}b=a.join("")}}return b},h1c=!1,f1c=!1,k1c=function(a,b,c,d){c=c.getFullYear();c<=0&&d&&(c=1-c);return i1c(a,j1c(c,b))},j1c=function(a,b){b==2&&(a%=100);a<0&&b++;return _.Tk(a,b)},l1c=function(a){if(!(a.getHours&&a.getSeconds&&a.getMinutes))throw Error("Rh");},m1c=function(a,b){l1c(b);b=e1c(b);return a.oa.Uqc[b>=12&&b<24?1:0]},g1c=function(a,b,c,d,e,f){var g=b.length;switch(b.charAt(0)){case "G":return c=d.getFullYear()>0?1:0,g>=4?a.oa.KTd[c]:a.oa.J5c[c];case "y":return k1c(a,g,
d,!0);case "Y":return c=d.getFullYear(),e=d.getMonth(),d=d.getDate(),c=V0c(c,e,d,a.oa.v2b,a.oa.Ppb),c=(new Date(c)).getFullYear(),g==2&&(c%=100),i1c(a,j1c(c,g));case "u":return k1c(a,g,d,!1);case "M":a:switch(c=d.getMonth(),g){case 5:g=a.oa.zXd[c];break a;case 4:g=a.oa.g3b[c];break a;case 3:g=a.oa.l3b[c];break a;default:g=i1c(a,_.Tk(c+1,g))}return g;case "k":return l1c(e),c=e1c(e)||24,i1c(a,_.Tk(c,g));case "S":return i1c(a,(e.getMilliseconds()/1E3).toFixed(Math.min(3,g)).slice(2)+(g>3?_.Tk(0,g-3):
""));case "E":return c=d.getDay(),g>=4?a.oa.A3b[c]:a.oa.m3b[c];case "a":return m1c(a,e);case "b":return m1c(a,e);case "B":return m1c(a,e);case "h":return l1c(e),c=e1c(e)%12||12,i1c(a,_.Tk(c,g));case "K":return l1c(e),c=e1c(e)%12,i1c(a,_.Tk(c,g));case "H":return l1c(e),c=e1c(e),i1c(a,_.Tk(c,g));case "c":a:switch(c=d.getDay(),g){case 5:g=a.oa.o3b[c];break a;case 4:g=a.oa.V7c[c];break a;case 3:g=a.oa.ztc[c];break a;default:g=i1c(a,_.Tk(c,1))}return g;case "L":a:switch(c=d.getMonth(),g){case 5:g=a.oa.VZd[c];
break a;case 4:g=a.oa.sqb[c];break a;case 3:g=a.oa.U7c[c];break a;default:g=i1c(a,_.Tk(c+1,g))}return g;case "Q":return c=Math.floor(d.getMonth()/3),g<4?a.oa.O7c[c]:a.oa.I7c[c];case "d":return i1c(a,_.Tk(d.getDate(),g));case "m":return l1c(e),i1c(a,_.Tk(e.getMinutes?e.getMinutes():0,g));case "s":return l1c(e),i1c(a,_.Tk(e.getSeconds(),g));case "v":return(f||_.Z0c(c.getTimezoneOffset())).Ba;case "V":return a=f||_.Z0c(c.getTimezoneOffset()),g<=2?a.Ba:$0c(a,c)>0?a.oa.sTd!==void 0?a.oa.sTd:a.oa.DST_GENERIC_LOCATION:
a.oa.a8c!==void 0?a.oa.a8c:a.oa.STD_GENERIC_LOCATION;case "w":return c=e.getFullYear(),d=e.getMonth(),e=e.getDate(),c=V0c(c,d,e,a.oa.v2b,a.oa.Ppb),i1c(a,_.Tk(Math.floor(Math.round((c-(new Date((new Date(c)).getFullYear(),0,1)).valueOf())/864E5)/7)+1,g));case "z":return a=f||_.Z0c(c.getTimezoneOffset()),g<4?a.R0(c):a.Ca[$0c(a,c)>0?3:1];case "Z":return d=f||_.Z0c(c.getTimezoneOffset()),g<4?(g=-_.a1c(d,c),a=[g<0?"-":"+"],g=Math.abs(g),a.push(_.Tk(Math.floor(g/60)%100,2),_.Tk(g%60,2)),g=a.join("")):g=
i1c(a,Y0c(_.a1c(d,c))),g;default:return""}};
var zde;_.yde=function(a,b){this.oa=a;this.Aa=b||_.ee()};zde=function(a){this.oa=a.Aa.clone();this.Aa=Number(a.oa.Tj())};_.Dh(zde,_.Yn);zde.prototype.next=function(){if(Number(this.oa.Tj())>this.Aa)return _.oMa;const a=this.oa.clone();this.oa.add(new _.AC("d",1));return _.pMa(a)};var Ade=function(){this.Aa=_.Zfd;this.oa=_.$fd};Ade.prototype.contains=function(a){return a.valueOf()>=this.Aa.valueOf()&&a.valueOf()<=this.oa.valueOf()};Ade.prototype.iterator=function(){return new zde(this)};_.yde.prototype.Ea=function(a,b,c,d){b?(d=this.Aa.createElement("TD"),d.colSpan=c?1:2,Bde(this,d,"\u00ab",this.oa+"-previousMonth"),a.appendChild(d),d=this.Aa.createElement("TD"),d.colSpan=c?6:5,d.className=this.oa+"-monthyear",a.appendChild(d),d=this.Aa.createElement("TD"),Bde(this,d,"\u00bb",this.oa+"-nextMonth"),a.appendChild(d)):(c=this.Aa.createElement("TD"),c.colSpan=5,Bde(this,c,"\u00ab",this.oa+"-previousMonth"),Bde(this,c,"",this.oa+"-month"),Bde(this,c,"\u00bb",this.oa+"-nextMonth"),b=this.Aa.createElement("TD"),
b.colSpan=3,Bde(this,b,"\u00ab",this.oa+"-previousYear"),Bde(this,b,"",this.oa+"-year"),Bde(this,b,"\u00bb",this.oa+"-nextYear"),d.indexOf("y")<d.indexOf("m")?(a.appendChild(b),a.appendChild(c)):(a.appendChild(c),a.appendChild(b)))};
_.yde.prototype.Ba=function(a,b){let c=this.Aa.createElement("TD");c.colSpan=b?2:3;c.className=this.oa+"-today-cont";Bde(this,c,"Today",this.oa+"-today-btn");a.appendChild(c);c=this.Aa.createElement("TD");c.colSpan=b?4:3;a.appendChild(c);c=this.Aa.createElement("TD");c.colSpan=2;c.className=this.oa+"-none-cont";Bde(this,c,"None",this.oa+"-none-btn");a.appendChild(c)};
var Bde=function(a,b,c,d){const e=[a.oa+"-btn"];d&&e.push(d);d=a.Aa.createElement("BUTTON");d.className=e.join(" ");d.appendChild(a.Aa.createTextNode(c));b.appendChild(d)};var Ide,Nde,Kde;
_.UF=function(a,b,c,d){_.qn.call(this,c);this.Ca=b||_.zC;this.Yb=this.Ca.ztc;this.Pd=new _.KC("d",this.Ca);new _.KC("dd",this.Ca);this.wg=new _.KC("w",this.Ca);this.Kf=new _.KC("d MMM",this.Ca);this.Nb=new _.KC(_.LC.D3b||"y",this.Ca);this.Ld=new _.KC(_.LC.Gab||"MMMM y",this.Ca);this.qc=d||new _.yde(this.Xz(),this.oa);this.Ba=new _.BC(a);this.Ba.reb=this.Ca.v2b;this.Ba.kLa=this.Ca.Ppb;this.Aa=this.Ba.clone();this.Aa.setDate(1);this.Cb="      ".split(" ");this.Cb[this.Ca.D8c[0]]=this.Xz()+"-wkend-start";
this.Cb[this.Ca.D8c[1]]=this.Xz()+"-wkend-end";this.Va={};this.Pa=[];this.Qb=0};_.Dh(_.UF,_.qn);_.aa=_.UF.prototype;_.aa.vmc=!0;_.aa.aqc=new Ade;_.aa.Dmc=!0;_.aa.Emc=!0;_.aa.arb=!0;_.aa.Cmc=!0;_.aa.sZc=!1;_.aa.f7b=null;_.aa.o8b=null;_.aa.n8b=null;_.aa.m8b=null;_.aa.y7d=_.LJa.getInstance();_.aa.Xz=function(){return"goog-date-picker"};_.Ede=function(a){a.sZc=!0;Cde(a);_.Dde(a)};_.Gde=function(a){a.Dmc=!1;Cde(a);Fde(a);_.Dde(a)};_.Hde=function(a){_.Jm(a.Bb,a.Cmc);_.Jm(a.hb,a.arb);_.Jm(a.Dd,a.Cmc||a.arb)};
_.aa=_.UF.prototype;_.aa.hUc=function(){this.Aa.add(new _.AC("m",-1));_.Dde(this);Ide(this)};_.aa.lsc=function(){this.Aa.add(new _.AC("m",1));_.Dde(this);Ide(this)};_.aa.SVd=function(){this.Aa.add(new _.AC("y",-1));_.Dde(this);Ide(this)};_.aa.RVd=function(){this.Aa.add(new _.AC("y",1));_.Dde(this);Ide(this)};_.aa.TGd=function(){const a=new _.BC;this.aqc.contains(a)&&this.setDate(a)};_.aa.GXc=function(){this.arb&&this.setDate(null)};_.aa.getDate=function(){return this.Ba&&this.Ba.clone()};
_.aa.setDate=function(a){Jde(this,a,!0)};
var Jde=function(a,b,c){const d=b==a.Ba||b&&a.Ba&&b.getFullYear()==a.Ba.getFullYear()&&b.getMonth()==a.Ba.getMonth(),e=b==a.Ba||d&&b.getDate()==a.Ba.getDate();a.Ba=b&&new _.BC(b);b&&(a.Aa.set(a.Ba),a.Aa.setFullYear(a.Ba.getFullYear()),a.Aa.setDate(1));_.Dde(a);c&&a.dispatchEvent(new Kde("select",a,a.Ba));e||a.dispatchEvent(new Kde("change",a,a.Ba));d||Ide(a)},Cde=function(a){if(a.o8b){for(var b=a.o8b;b.firstChild;)b.removeChild(b.firstChild);var c=a.Ca.lRa[0].toLowerCase();a.qc.Ea(b,a.sZc,a.Dmc,c);
if(a.sZc){Lde(a,b,a.Xz()+"-previousMonth",a.hUc);if(c=_.Ql(a.Xz()+"-previousMonth",b))_.Rm(c,"hidden",!0),c.tabIndex=-1;Lde(a,b,a.Xz()+"-nextMonth",a.lsc);if(c=_.Ql(a.Xz()+"-nextMonth",b))_.Rm(c,"hidden",!0),c.tabIndex=-1;a.n8b=_.Ql(a.Xz()+"-monthyear",b)}else Lde(a,b,a.Xz()+"-previousMonth",a.hUc),Lde(a,b,a.Xz()+"-nextMonth",a.lsc),Lde(a,b,a.Xz()+"-month",a.LPe),Lde(a,b,a.Xz()+"-previousYear",a.SVd),Lde(a,b,a.Xz()+"-nextYear",a.RVd),Lde(a,b,a.Xz()+"-year",a.aQe),a.Na=_.Ql(a.Xz()+"-month",b),c=_.ee(),
b=_.Ql(a.Xz()+"-year",b||c.oa),a.wb=b}},Lde=function(a,b,c,d){b=_.Ql(c,b);_.rn(a).listen(b,"click",function(e){e.preventDefault();d.call(this,e)})},Fde=function(a){if(a.m8b){var b=a.m8b;_.bm(b);a.qc.Ba(b,a.Dmc);Lde(a,b,a.Xz()+"-today-btn",a.TGd);Lde(a,b,a.Xz()+"-none-btn",a.GXc);a.Bb=_.Ql(a.Xz()+"-today-btn",b);a.hb=_.Ql(a.Xz()+"-none-btn",b);_.Hde(a)}};_.aa=_.UF.prototype;
_.aa.uX=function(a){_.UF.xf.uX.call(this,a);_.yl.add(a,this.Xz());const b=this.oa.zq("TABLE",{role:"presentation"}),c=this.oa.zq("THEAD"),d=this.oa.zq("TBODY",{role:"grid"}),e=this.oa.zq("TFOOT");d.tabIndex=0;this.vd=d;this.Dd=e;let f=this.oa.zq("TR",{role:"row"});f.className=this.Xz()+"-head";this.o8b=f;Cde(this);c.appendChild(f);let g;this.Ea=[];for(let h=0;h<7;h++){f=this.oa.createElement("TR");this.Ea[h]=[];for(let k=0;k<8;k++)g=this.oa.createElement(k==0||h==0?"th":"td"),k!=0&&h!=0||k==h?h!==
0&&k!==0&&(_.Qm(g,"gridcell"),g.setAttribute("tabindex","-1")):(g.className=k==0?this.Xz()+"-week":this.Xz()+"-wday",_.Qm(g,k==0?"rowheader":"columnheader")),f.appendChild(g),this.Ea[h][k]=g;d.appendChild(f)}f=this.oa.createElement("TR");f.className=this.Xz()+"-foot";this.m8b=f;Fde(this);e.appendChild(f);b.cellSpacing="0";b.cellPadding="0";b.appendChild(c);b.appendChild(d);b.appendChild(e);a.appendChild(b);_.Mde(this);_.Dde(this);a.tabIndex=0};_.aa.eS=function(){_.UF.xf.eS.call(this);this.uX(this.Ia())};
_.aa.jz=function(){_.UF.xf.jz.call(this);const a=_.rn(this);a.listen(this.vd,"click",this.Sle);a.listen(Nde(this,this.Ia()),"key",this.Tle)};_.aa.oS=function(){_.UF.xf.oS.call(this);this.Ta();for(const a in this.Va)this.Va[a].dispose();this.Va={}};_.aa.create=_.UF.prototype.Ks;_.aa.ud=function(){_.UF.xf.ud.call(this);this.hb=this.Bb=this.wb=this.n8b=this.Na=this.m8b=this.o8b=this.Dd=this.vd=this.Ea=null};
_.aa.Sle=function(a){if(a.target.tagName=="TD"){let b,c=-2,d=-2;for(b=a.target;b;b=b.previousSibling,c++);for(b=a.target.parentNode;b;b=b.previousSibling,d++);a=this.Pa[d][c];this.aqc.contains(a)&&this.setDate(a.clone())}};
_.aa.Tle=function(a){let b,c;switch(a.keyCode){case 33:a.preventDefault();b=-1;break;case 34:a.preventDefault();b=1;break;case 37:a.preventDefault();c=-1;break;case 39:a.preventDefault();c=1;break;case 38:a.preventDefault();c=-7;break;case 40:a.preventDefault();c=7;break;case 36:a.preventDefault();this.TGd();break;case 46:a.preventDefault();this.GXc();break;case 13:case 32:a.preventDefault(),Jde(this,this.Ba,!0);default:return}this.Ba?(a=this.Ba.clone(),a.add(new _.AC(0,b,c))):(a=this.Aa.clone(),
a.setDate(1));this.aqc.contains(a)&&(Jde(this,a,!1),this.KD.focus())};_.aa.LPe=function(a){a.stopPropagation();a=[];for(let b=0;b<12;b++)a.push(this.Ca.sqb[b]);Ode(this,this.Na,a,this.ame,this.Ca.sqb[this.Aa.getMonth()])};_.aa.aQe=function(a){a.stopPropagation();a=[];const b=this.Aa.getFullYear(),c=this.Aa.clone();for(let d=-5;d<=5;d++)c.setFullYear(b+d),a.push(this.Nb.format(c));Ode(this,this.wb,a,this.pme,this.Nb.format(this.Aa))};
_.aa.ame=function(a){a=Number(a.getAttribute("itemIndex"));this.Aa.setMonth(a);_.Dde(this);this.Na.focus&&this.Na.focus()};_.aa.pme=function(a){a.firstChild.nodeType==3&&(a=Number(a.getAttribute("itemIndex")),this.Aa.setFullYear(this.Aa.getFullYear()+a-5),_.Dde(this));this.wb.focus()};
var Ode=function(a,b,c,d,e){a.Ta();const f=a.oa.createElement("DIV");f.className=a.Xz()+"-menu";a.Wa=null;const g=a.oa.createElement("UL");for(let h=0;h<c.length;h++){const k=a.oa.zq("LI",null,c[h]);k.setAttribute("itemIndex",h);c[h]==e&&(a.Wa=k);g.appendChild(k)}f.appendChild(g);f.style.left=b.offsetLeft+b.parentNode.offsetLeft+"px";f.style.top=b.offsetTop+"px";f.style.width=b.clientWidth+"px";a.Na.parentNode.appendChild(f);a.Ka=f;a.Wa||(a.Wa=g.firstChild);a.Wa.className=a.Xz()+"-menu-selected";
a.Vb=d;b=_.rn(a);b.listen(a.Ka,"click",a.Kc);b.listen(Nde(a,a.Ka),"key",a.Lc);b.listen(a.oa.getDocument(),"click",a.Ta);f.tabIndex=0;f.focus()};_.UF.prototype.Kc=function(a){a.stopPropagation();this.Ta();this.Vb&&this.Vb(a.target)};
_.UF.prototype.Lc=function(a){a.stopPropagation();let b;const c=this.Wa;switch(a.keyCode){case 35:a.preventDefault();b=c.parentNode.lastChild;break;case 36:a.preventDefault();b=c.parentNode.firstChild;break;case 38:a.preventDefault();b=c.previousSibling;break;case 40:a.preventDefault();b=c.nextSibling;break;case 13:case 9:case 0:a.preventDefault(),this.Ta(),this.Vb(c)}b&&b!=c&&(c.className="",b.className=this.Xz()+"-menu-selected",this.Wa=b)};
_.UF.prototype.Ta=function(){if(this.Ka){const a=_.rn(this);a.unlisten(this.Ka,"click",this.Kc);a.unlisten(Nde(this,this.Ka),"key",this.Lc);a.unlisten(this.oa.getDocument(),"click",this.Ta);_.fm(this.Ka);delete this.Ka}};
_.Dde=function(a){if(a.Ia()){var b=a.Aa.clone();b.setDate(1);a.n8b&&_.im(a.n8b,a.Ld.format(b));a.Na&&_.im(a.Na,a.Ca.sqb[b.getMonth()]);a.wb&&_.im(a.wb,a.Nb.format(b));var c=_.T0c(b);_.U0c(b);b.add(new _.AC("m",-1));b.setDate(_.U0c(b)-(c-1));c=new _.AC("d",1);a.Pa=[];for(let d=0;d<6;d++){a.Pa[d]=[];for(let e=0;e<7;e++){a.Pa[d][e]=b.clone();let f=b.getFullYear();b.add(c);b.getMonth()==0&&b.getDate()==1&&f++;b.setFullYear(f)}}_.Pde(a)}};
_.Pde=function(a){if(a.Ia()){var b=a.Aa.getMonth(),c=new _.BC,d=c.getFullYear(),e=c.getMonth();c=c.getDate();var f=6;for(let n=0;n<6;n++){a.Dmc?(_.im(a.Ea[n+1][0],a.wg.format(a.Pa[n][0])),_.yl.set(a.Ea[n+1][0],a.Xz()+"-week")):(_.im(a.Ea[n+1][0],""),_.yl.set(a.Ea[n+1][0],""));for(var g=0;g<7;g++){var h=a.Pa[n][g],k=a.Ea[n+1][g+1];k.id||(k.id=_.MJa(a.y7d));_.Qm(k,"gridcell");_.iIa(k,a.Kf.format(h));const q=[a.Xz()+"-date"];a.aqc.contains(h)||q.push(a.Xz()+"-unavailable-date");h.getMonth()!=b&&q.push(a.Xz()+
"-other-month");var l=(g+a.Aa.kLa+7)%7;a.Cb[l]&&q.push(a.Cb[l]);h.getDate()==c&&h.getMonth()==e&&h.getFullYear()==d&&q.push(a.Xz()+"-today");a.Ba&&h.getDate()==a.Ba.getDate()&&h.getMonth()==a.Ba.getMonth()&&h.getFullYear()==a.Ba.getFullYear()&&(q.push(a.Xz()+"-selected"),a.KD=k);a.f7b&&(l=a.f7b(h))&&q.push(l);h=a.Pd.format(h);_.im(k,h);_.yl.set(k,q.join(" "))}n>=4&&(g=a.Ea[n+1][0].parentElement||a.Ea[n+1][0].parentNode,k=a.Pa[n][0].getMonth()==b,_.Jm(g,k||a.vmc),k||(f=Math.min(f,n)))}b=(a.vmc?6:f)+
(a.Emc?1:0);a.Qb!=b&&(a.Qb<b&&a.dispatchEvent("gridSizeIncrease"),a.Qb=b)}};Ide=function(a){const b=new Kde("changeActiveMonth",a,a.Aa.clone());a.dispatchEvent(b)};_.Mde=function(a){if(a.Ia()){if(a.Emc)for(let b=0;b<7;b++)_.im(a.Ea[0][b+1],a.Yb[((b+a.Aa.kLa+7)%7+1)%7]);_.Jm(a.Ea[0][0].parentElement||a.Ea[0][0].parentNode,a.Emc)}};Nde=function(a,b){const c=_.be(b);c in a.Va||(a.Va[c]=new _.AD(b));return a.Va[c]};Kde=function(a,b,c){_.Vm.call(this,a,b);this.date=c};_.Dh(Kde,_.Vm);
var kde,lde,mde;kde=/^[ \t\xA0\u1680\u180e\u2000-\u200a\u202f\u205f\u3000]/;lde=/^[\s\xA0\u1680\u180e\u2000-\u200a\u202f\u205f\u3000]+/;_.nde=function(a){this.oa=[];this.Aa=_.zC;if(typeof a=="number"){let b;a>11&&(a=10);a<4?b=this.Aa.lRa[a]:a<8?b=this.Aa.uqb[a-4]:(b=this.Aa.z5c[a-8],b=b.replace("{1}",this.Aa.lRa[a-8]),b=b.replace("{0}",this.Aa.uqb[a-8]));mde(this,b)}else mde(this,a)};
mde=function(a,b){var c=!1;let d="";for(let g=0;g<b.length;g++){const h=b.charAt(g);if(kde.test(h))for(d.length>0&&(a.oa.push({text:d,count:0,Nab:!1,numeric:!1}),d=""),a.oa.push({text:" ",count:0,Nab:!1,numeric:!1});g<b.length-1&&b.charAt(g+1)==" ";)g++;else if(c)h=="'"?g+1<b.length&&b.charAt(g+1)=="'"?(d+="'",g++):c=!1:d+=h;else if("GyMdkHmsSEDabBhKzZvQL".indexOf(h)>=0){d.length>0&&(a.oa.push({text:d,count:0,Nab:!1,numeric:!1}),d="");for(var e=b.charAt(g),f=g+1;f<b.length&&b.charAt(f)==e;)f++;e=
f-g;e<=0?f=!1:(f="MydhHmsSDkK".indexOf(h),f=f>0||f==0&&e<3);a.oa.push({text:h,count:e,Nab:!1,numeric:f});g+=e-1}else h=="'"?g+1<b.length&&b.charAt(g+1)=="'"?(d+="'",g++):c=!0:d+=h}d.length>0&&a.oa.push({text:d,count:0,Nab:!1,numeric:!1});b=!1;for(c=0;c<a.oa.length;c++)a.oa[c].numeric?!b&&c+1<a.oa.length&&a.oa[c+1].numeric&&(b=!0,a.oa[c].Nab=!0):b=!1};
_.nde.prototype.parse=function(a,b,c){var d=!1,e=!1;c&&(d=c.f1f||!1,e=c.validate||!1);if(d)for(c=0;c<this.oa.length;c++){var f=this.oa[c];if(f.count>0&&("abBhHkKm".indexOf(f.text.charAt(0))<0||f.count>2||f.Nab))throw Error("an`"+f.text.charAt(0));}f=new ode;c=[0];f.Ha=-1;for(let n=0;n<this.oa.length&&!(d&&c[0]>=a.length);n++){if(this.oa[n].count==0){a:{var g=a;var h=c,k=this.oa[n],l=d;if(k.text.match(kde)!=null){if(k=h[0],pde(g,h),h[0]>k){g=!0;break a}}else{if(g.indexOf(k.text,h[0])==h[0]){h[0]+=
k.text.length;g=!0;break a}if(l&&k.text.indexOf(g.substring(h[0]))==0){h[0]+=g.length-h[0];g=!0;break a}}g=!1}if(g)continue;return 0}if(this.oa[n].Nab){a:{g=a;h=c;k=n;const q=h[0];let r=0;for(l=k;l<this.oa.length;l++){const v=this.oa[l];let B=v.count;if(B===0)break;if(l==k&&(B-=r,r++,B==0)){g=0;break a}const G=l>k&&v.numeric,M=h[0];if(!qde(this,g,h,v,B,f,!1)||G&&h[0]-M<B)l=k-1,h[0]=q}g=l-k}if(g<=0)return 0;n+=g-1}else if(!qde(this,a,c,this.oa[n],0,f,d))return 0}a:{a=e;if(b==null)throw Error("bn");
f.era!=void 0&&f.year!=void 0&&f.era==0&&f.year>0&&(f.year=-(f.year-1));f.year!=void 0&&b.setFullYear(f.year);d=b.getDate();b.setDate(1);f.month!=void 0&&b.setMonth(f.month);f.day!=void 0?b.setDate(f.day):(e=_.P_c(b.getFullYear(),b.getMonth()),b.setDate(d>e?e:d));typeof b.setHours==="function"&&(f.hours==void 0&&(f.hours=b.getHours()),f.hours<12&&(f.Ea!=void 0&&f.Ea>0?f.hours+=12:f.Ba!==void 0&&("isPm noon afternoon1 afternoon2 evening1 evening2".split(" ").includes(f.Ba)||["night1","night2"].includes(f.Ba)&&
f.hours>=6)&&(f.hours+=12)),b.setHours(f.hours));typeof b.setMinutes==="function"&&f.minutes!=void 0&&b.setMinutes(f.minutes);typeof b.setSeconds==="function"&&f.tT!=void 0&&b.setSeconds(f.tT);typeof b.setMilliseconds==="function"&&f.oa!=void 0&&b.setMilliseconds(f.oa);if(a&&(f.year&&f.year!=b.getFullYear()||f.month&&f.month!=b.getMonth()||f.day&&f.day!=b.getDate()||f.hours&&f.hours>=24||f.minutes&&f.minutes>=60||f.tT&&f.tT>=60||f.oa&&f.oa>=1E3))b=!1;else{f.Ca!=void 0&&(a=b.getTimezoneOffset(),b.setTime(b.getTime()+
(f.Ca-a)*60*1E3));f.Da&&(a=new Date,a.setFullYear(a.getFullYear()-80),b.getTime()<a.getTime()&&b.setFullYear(a.getFullYear()+100));if(f.Aa!=void 0)if(f.day==void 0)f=(7+f.Aa-b.getDay())%7,f>3&&(f-=7),a=b.getMonth(),b.setDate(b.getDate()+f),b.getMonth()!=a&&b.setDate(b.getDate()+(f>0?-7:7));else if(f.Aa!=b.getDay()){b=!1;break a}b=!0}}return b?c[0]:0};
var qde=function(a,b,c,d,e,f,g){pde(b,c);if(d.numeric&&e>0&&c[0]+e>b.length)return!1;switch(d.text.charAt(0)){case "G":return rde(b,c,[a.Aa.J5c],h=>f.era=h),!0;case "M":case "L":return sde(a,b,c,e,d,f);case "E":return rde(b,c,[a.Aa.A3b,a.Aa.m3b],h=>f.Aa=h);case "B":case "b":return e=[],a=[[].concat(a.Aa.Uqc)],e.push("isAm"),e.push("isPm"),b=rde(b,c,a,h=>f.Ha=h,g),f.Ba=e[f.Ha],g?b:!0;case "a":return b=rde(b,c,[a.Aa.Uqc],h=>f.Ea=h,g),g?b:!0;case "y":return tde(a,b,c,d,e,f);case "Q":return rde(b,c,[a.Aa.I7c,
a.Aa.O7c],function(h){f.month=h*3;f.day=1});case "d":return ude(a,b,c,d,e,function(h){f.day=h}),!0;case "S":return vde(a,b,c,e,f);case "h":case "K":case "H":case "k":return b=ude(a,b,c,d,e,function(h){f.hours=d.text.charAt(0)==="h"&&h===12?0:h},g),g?b:!0;case "m":return b=ude(a,b,c,d,e,function(h){f.minutes=h},g),g?b:!0;case "s":return ude(a,b,c,d,e,function(h){f.tT=h}),!0;case "z":case "Z":case "v":return wde(a,b,c,f);default:return!1}},tde=function(a,b,c,d,e,f){const g=c[0];e=xde(a,b,c,e);e===null&&
(e=xde(a,b,c,0,!0));if(e===null)return!1;e>=0&&c[0]-g==2&&d.count==2?(a=e,b=(new Date).getFullYear()-80,c=b%100,f.Da=a==c,a+=Math.floor(b/100)*100+(a<c?100:0),f.year=a):f.year=e;return!0},sde=function(a,b,c,d,e,f){return e.numeric&&ude(a,b,c,e,d,function(g){f.month=g-1})?!0:rde(b,c,[a.Aa.g3b,a.Aa.sqb,a.Aa.l3b,a.Aa.U7c],function(g){f.month=g})},vde=function(a,b,c,d,e){const f=c[0];a=xde(a,b,c,d);if(a===null)return!1;c=c[0]-f;e.oa=c<3?a*Math.pow(10,3-c):Math.round(a/Math.pow(10,c-3));return!0},wde=
function(a,b,c,d){b.indexOf("GMT",c[0])==c[0]&&(c[0]+=3);if(c[0]>=b.length)return d.Ca=0,!0;const e=c[0];let f=xde(a,b,c,0,!0);if(f===null)return!1;let g;if(c[0]<b.length&&b.charAt(c[0])==":"){g=f*60;c[0]++;f=xde(a,b,c,0);if(f===null)return!1;g+=f}else g=f,g=g<24&&c[0]-e<=3?g*60:g%100+g/100*60;d.Ca=-g;return!0},ude=function(a,b,c,d,e,f,g){g=g||!1;const h=c[0];a=xde(a,b,c,e);if(a===null)return!1;if(g&&c[0]-h<d.count){if(c[0]<b.length)return!1;a*=Math.pow(10,d.count-(c[0]-h))}f(a);return!0},rde=function(a,
b,c,d,e){e=e||!1;for(let k=0;k<c.length;k++){var f=b;var g=c[k],h=e;let l=0,n=null;const q=a.substring(f[0]).toLowerCase();for(let r=0;r<g.length;r++){const v=g[r].toLowerCase();if(h&&v.indexOf(q)==0){l=q.length;n=r;break}g[r].length>l&&q.indexOf(v)==0&&(l=g[r].length,n=r)}n!==null&&(f[0]+=l);f=n;if(f!==null)return d(f),!0}return!1},pde=function(a,b){(a=a.substring(b[0]).match(lde))&&(b[0]+=a[0].length)},xde=function(a,b,c,d,e){b=d>0?b.substring(0,c[0]+d):b;e=e||!1;if(a.Aa.Ytc){d=[];for(let f=c[0];f<
b.length;f++){const g=b.charCodeAt(f)-a.Aa.Ytc;d.push(0<=g&&g<=9?String.fromCharCode(g+48):b.charAt(f))}b=d.join("")}else b=b.substring(c[0]);a=b.match(new RegExp(`^${e?"[+-]?":""}\\d+`));if(!a)return null;c[0]+=a[0].length;return parseInt(a[0],10)},ode=function(){};ode.prototype.Da=!1;
_.t("VD4Qme");
var YsB=function(){var a={OouJcb:"cd_min",rzG2be:"cd_max"};const b=_.Il("HjtPBb");if(b)for(const c in a){const d=_.Il(c);b.value=b.value.replace(new RegExp("("+a[c]+":)([^,]*)"),`$1${_.WsB(d.value).replace(/^\s+|\s+$/g,"")}`)}},$sB=function(a){var b=ZsB();a.f7b=b},atB=_.L_c.lRa[3],btB=function(a,b){const c=new Date,d=new _.nde(atB);b=b.value.trim();if(b.length===0||d.parse(b,c,{validate:!0})!==b.length)a.oa.GXc();else{a.Ba=!1;try{a.oa.setDate(c)}finally{a.Ba=!0}}},ctB=function(a){const b=a.oa.getDate();
if(a.Ba&&b){var c=new _.KC(atB.replace(/yy/,"y"));a.Aa.value=c.format(b);a.Aa.id==="OouJcb"?_.Jl("rzG2be").focus():a.Aa.focus()}},dtB=function(a,b){const c=_.Ql("qomYCd",a.container);_.yl.enable(c,"KbfSHd",b.id!=="OouJcb");(0,_.Un)(()=>{_.yl.add(c,"lRiKjb");(0,_.re)(()=>{_.yl.remove(c,"lRiKjb")})},150)},etB=function(){var a=_.Ql("goog-date-picker-head");return a&&(a=_.Pl("goog-date-picker-btn",a))&&a.length>1?a[1]:null},ZsB=function(){const a=new Date(Date.now());a.setDate(28);let b;const c=new Date(Date.now());
return d=>{b||(b=etB());b&&_.yl.enable(b,"suap3e",Number(a)<=Number(d));return Number(d)<=Number(c)?null:"suap3e"}},ftB=function(a){const b=_.Xl("DIV","UfY8P");_.dHa(_.Ql("NwEGxd",a.container),b);const c=new _.UF;_.Gde(c);c.Cmc=!1;c.Bb&&_.Hde(c);c.vmc=!0;_.Dde(c);c.arb=!0;c.hb&&_.Hde(c);c.Yb=c.Ca.o3b;_.Mde(c);_.Ede(c);$sB(c);c.Ks(b);a.oa=c;const d=_.Ql("Gwgzqd",a.container),e=_.Ql("Ru1Ao",a.container);_.fe(c,"select",()=>ctB(a));_.fe(d,"keydown",f=>{f.keyCode===9&&f.shiftKey&&(f.preventDefault(),
e.focus())});_.fe(e,"keydown",f=>{f.keyCode!==9||f.shiftKey||(f.preventDefault(),d.focus())});_.fe(e,"click",()=>{const f=[_.Il("OouJcb"),_.Il("rzG2be")],g=new Date,h=new _.nde(atB),k=new _.KC(atB.replace(/yy/,"y"));for(let l=0;l<f.length;l++){const n=f[l],q=n.value.trim();q.length!==0&&h.parse(q,g,{validate:!0})===q.length&&(n.value=k.format(g))}})},gtB=class extends _.Wr{constructor(a){super(a.Oa);this.oa=this.container=this.Aa=null;this.Ba=!0}Ha(){return this.Aa}Ea(){return this.oa}Na(){ctB(this)}Ka(){return etB()}Ma(){return ZsB()}Ca(a){this.Aa=
a=a.qb.el();dtB(this,a);btB(this,a)}Pa(a){if(!this.container){this.container=this.Ia("b6oohe").kb();ftB(this);const c=Math.max(_.cs(this,this.container,"kJX8be").el().clientWidth,_.cs(this,this.container,"RltH6b").el().clientWidth),d=_.Qy()?"right":"left";this.container.style[d]=`${c}px`;_.Ql("NwEGxd",this.container).style[d]=`${c}px`}const b=_.Il("OouJcb");btB(this,b);this.xc("Fg3TAc",_.wo).then(c=>{(0,_.re)(()=>{c.oa(b,a)})})}onSubmit(){YsB()}Da(){YsB();_.Il("T3kYXe").submit()}};
gtB.prototype.$wa$hNEEAb=function(){return this.Da};gtB.prototype.$wa$zbvklb=function(){return this.onSubmit};gtB.prototype.$wa$EEGHee=function(){return this.Pa};gtB.prototype.$wa$daRB0b=function(){return this.Ca};gtB.prototype.$wa$Kpa0wd=function(){return this.Ma};gtB.prototype.$wa$jFBxGd=function(){return this.Ka};gtB.prototype.$wa$VUQXyf=function(){return this.Na};gtB.prototype.$wa$wUeKKe=function(){return this.Ea};gtB.prototype.$wa$wKX3te=function(){return this.Ha};_.Yr(_.XsB,gtB);
_.u();
_.t("VEbNoe");
var $Tb,aUb,dUb,bUb,cUb,fUb,eUb,gUb;$Tb=function(a,b,c){a.Da||(a.open(b,c),a.trigger("zcw91"))};
aUb=function(a,b,c){if(!a.Da){a.Da=!0;var d=a.getAnimation();d=_.Yv(_.lQb(_.bw(_.$v(new _.cw,d),1)),h=>{if(a.Va&&h.eventType===2)h=!1;else{var k={};k.ibe=h.eventType;var l=void 0,n=null;a.Ea&&(n=a.Ea,l=n.event||void 0,n=(n=n.data)&&n.triggerElement||null,a.Ea=null);a.Bb||h.eventType===0?(a.Aa!=null&&a.Aa.mJc(n),k.rv=l,a.trigger("SJu0Rc",k),_.cn(a.Ba,"dg_dismissed",!1,k),a.Da=!1,h=!0):(k.rv=l,a.trigger("S5BwHc",k),h=!1)}return h});_.zo(a,a.getContent());var e=a.getData("bbena"),f=_.pl(e,""),g=[2];
a.Bb&&g.push(1);e.Lb()&&f&&(g.push(4),_.eQb(_.Zv(d,g),f,()=>{$Tb(a)}));c instanceof HTMLElement&&_.hQb(d,c);a.Pe.open(a.getContent(),d);a.handleResize();a.Pa=_.fe(a.Gb,"resize",()=>{a.handleResize()});a.Ca.length>0&&(a.Aa=a.Ca[0],a.Ca=[]);a.Aa!=null&&a.Aa.uZb(a.Ca.length!==0,b?b.qb.el():null)}};
dUb=function(a,b,c,d){if(!a.Da){a.Da=!0;var e=_.uw();a.Ba.parentNode!==e&&(e.appendChild(a.Ba),_.Jm(e,!0),a.Na=e.style.visibility,e.style.visibility="visible");_.yl.contains(a.CS(),"ivkdbf")||_.yl.add(a.CS(),"ivkdbf");_.yl.contains(a.getContent(),"ivkdbf")||_.yl.add(a.getContent(),"ivkdbf");_.yl.contains(a.getContainer(),"ivkdbf")||_.yl.add(a.getContainer(),"ivkdbf");a.handleResize();a.Pa=_.fe(a.Gb,"resize",()=>{a.handleResize()});a.Wa=d||document.activeElement;_.XTb(a.iT?a.iT:a.iT=new _.ZTb(a.getContent()));
a.Zm.isAvailable()&&a.Zm.enterBasicMode(16);bUb(a);cUb(a,()=>{$Tb(a,b,c)});a.Ca.length>0&&(a.Aa=a.Ca[0],a.Ca=[]);a.Aa!=null&&a.Aa.uZb(a.Ca.length!==0,b?b.qb.el():null);c&&c.focus?c.focus():(d=a.QLa(!0),d===a.getContent()&&(d.tabIndex=-1),d.focus())}};
bUb=function(a){a.Ka&&_.bn(a.Ka);a.Ka=_.fe(window,"scroll",d=>{const e=d.target;e&&!_.Of(a.getContainer(),e)&&_.Wm(d)},!0);if(a.Yb){var b=_.Wl(),c=a.SBa.get().Aa();b.scrollTop<c&&(b.scrollTop=c)}a.Ua=window.pageYOffset;b=a.hb;c=Number(b.style.top.replace("px",""));a.Ua=c?c*-1:window.pageYOffset;_.yl.contains(b,"TaoyYc")||(b.style.top=`-${a.Ua}px`,_.yl.add(b,"TaoyYc"))};
cUb=function(a,b){const c=a.getData("bbena"),d=_.pl(c,"")||a.getRoot().Sc("jsname");a.Ea=null;const e=[2];a.Hd&&e.push(1);c.Lb()&&d?(e.push(4),a.dismiss.listen(a.getContent(),f=>eUb(a,f),e,a.Mc,!1,!1,b,d)):a.dismiss.listen(a.getContent(),f=>eUb(a,f),e,a.Mc)};fUb=function(a){a.Ka&&(_.bn(a.Ka),a.Ka=null)};
eUb=function(a,b){if(a.Va&&b===2)return!1;const c={};c.dgdt=b;let d=void 0;var e=null;let f,g,h;const k=(h=(f=a.Ea)==null?void 0:(g=f.data)==null?void 0:g.osd)!=null?h:!1;a.Ea&&(e=a.Ea,d=e.event||void 0,e=(e=_.wf(e))&&e.triggerElement||null,a.Ea=null);if(a.Bb||b===0)return a.Aa!=null&&a.Aa.mJc(e),_.yl.remove(a.CS(),"ivkdbf"),_.yl.remove(a.getContent(),"ivkdbf"),_.yl.remove(a.getContainer(),"ivkdbf"),a.vd||_.zf(a.Ba)===a.getRoot().el()||a.getRoot().el().appendChild(a.Ba),k?fUb(a):a.HQ(),_.YTb(a.iT?
a.iT:a.iT=new _.ZTb(a.getContent())),a.Wa&&!k&&a.Wa.focus(),a.Zm.isAvailable()&&a.Zm.restoreToPreviousState(16),c.rv=d,a.trigger("SJu0Rc",c),_.cn(a.Ba,"dg_dismissed",!1,c),a.Da=!1,!0;c.rv=d;a.trigger("S5BwHc",c);return!1};gUb=function(a){return isNaN(a.Ua)?0:Number(a.Ua)-_.wTb()};
_.Gw=class extends _.Wr{static Sa(){return{jsdata:{Eeb:_.OTb},qe:{SBa:_.MTb},service:{Ue:_.Pu,dismiss:_.gw,focus:_.tw,overlay:_.Xv}}}constructor(a){super(a.Oa);this.Aa=this.content=this.container=this.overlay=null;this.Ca=[];this.contents={};this.Pa=this.Ka=this.Ea=this.iT=this.Wa=null;this.Va=this.Da=!1;this.Na=null;const b=a.jsdata.Eeb;this.dismiss=a.service.dismiss;this.Af=a.service.focus;this.Pe=a.service.overlay;this.SBa=a.qe.SBa;this.Mc=!!_.z(b,1);this.Gb=new _.uwa;this.Ba=this.Ya("XKSfm").el()||
_.Wmb(_.Te(this.getRoot().el(),"id")||"");_.zo(this,this.Ba);this.Bb=_.z(a.jsdata.Eeb,4)||!1;this.Hd=_.z(a.jsdata.Eeb,10)||!1;this.hb=this.Mc?document.documentElement:document.body;this.vd=!!_.z(a.jsdata.Eeb,6);this.Yb=!!_.z(a.jsdata.Eeb,7);this.Ma=_.wi(a.jsdata.Eeb,5);this.Dd=!!_.z(a.jsdata.Eeb,9);this.Zm=a.service.Ue;this.wb=this.getData("os").Lb()&&this.Ma===0;a=!_.yl.contains(this.Ba,"VH47ed");this.Ma===1&&a||this.Ma===2?this.open():this.Ma!==1||a||(eUb(this,0),_.yl.remove(this.Ba,"VH47ed"));
this.Cb()}Lc(){return this.Na}Jc(){return this.Ba}Kc(){return this.hb}yc(){return this.Ca}qc(){return this.Aa}Qb(){return this.contents}CS(){return this.overlay?this.overlay:this.overlay=_.Ql("kJFf0c",this.Ba)}Vb(){return this.CS()}getContainer(){return this.container?this.container:this.container=_.Ql("mcPPZ",this.Ba)}Rb(){return this.getContainer()}getContent(){return this.content?this.content:this.content=_.Ql("qk7LXc",this.Ba)}rc(){return this.getContent()}isOpen(){return this.Da}open(a,b,c){this.wb?
aUb(this,a,b):dUb(this,a,b,c)}getAnimation(){const a=[{element:this.getContent(),ju:"ivkdbf",hE:!0}],b=[{element:this.getContent(),ju:"ivkdbf",hE:!1}];return new _.kSb(a,b,250,250)}oa(a,b){this.open(b,a)}stopPropagation(){}XUa(){this.QLa(!1).focus()}YUa(){this.QLa(!0).focus()}QLa(a){const b=_.nw(this.Af,new _.io([this.getContent()])).toArray();return b.length===0?this.getContent():b[a?0:b.length-1]}close(a){this.wb?this.Nb(a):this.Mb(a)}Mb(a){this.Da&&(this.Ea=a||null,this.dismiss.dismiss(this.getContent()),
a=_.uw(),this.Na&&(a.style.visibility=this.Na,this.Na=null))}Nb(a){this.Da&&(this.Ea=a||null,this.Pe.close(this.getContent()))}Ta(a){_.fe(this.Ba,"dg_dismissed",a)}Ub(){this.wb===!0?this.Pe.close(this.getContent()):this.dismiss.hasListener(this.getContent())&&this.dismiss.dismiss(this.getContent());this.dismiss.unlisten(this.getContent());fUb(this);this.Pa&&(_.bn(this.Pa),this.Pa=null);this.Ba.__owner=null;_.zf(this.Ba)!==this.getRoot().el()&&this.getRoot().el().appendChild(this.Ba);super.Ub()}HQ(){const a=
this.hb;_.yl.remove(a,"TaoyYc");a.style.top="";if(window.scrollY!==gUb(this)&&(window.scrollTo(0,gUb(this)),this.getData("bbena").Lb()||this.Dd)){let b=0;const c=_.fe(window,"scroll",()=>{b++;window.scrollY<=50?(_.bn(c),window.scrollTo(0,gUb(this))):b>=2&&_.bn(c)},!0)}_.hn(()=>{fUb(this)});window.dispatchEvent(new Event("resize"));_.NTb(a)}wd(a){if(a)switch(a.type){case "KyPa0e":this.Va=!0;break;case "wjOG7e":this.Va=!1}}Cb(){const a=this.getData("bbena"),b=_.pl(a,"")||this.getRoot().Sc("jsname");
a.Lb()&&b&&this.dismiss.Wa(()=>{$Tb(this)},b)}Nc(a){a=_.wf(a).controller;var b=!_.yl.contains(this.Ba,"VH47ed");this.Aa==null&&a.isDefault()?(this.Aa=a,this.Ma===1&&b||this.Ma===2||this.isOpen()?a.uZb(this.Ca.length!==0,null):a.show(!1)):a.hide();b=a.getId();b!=null&&b!==""&&(this.contents[b]=a);a.EHd(this.getRoot().el())}Ha(a,b){this.contents[a]&&(this.Aa!=null&&(this.Ca.push(this.Aa),this.Aa.hide()),this.Aa=a=this.contents[a],a.uZb(!0,b))}handleResize(){if(window.visualViewport&&window.visualViewport.scale<
1&&_.Lm(this.getContainer())){let a;const b=Math.abs(((a=window.visualViewport)==null?void 0:a.pageLeft)||0);_.tm(this.getContainer(),{left:`${b}px`,right:"inherit",width:`${window.innerWidth}px`});_.tm(this.CS(),{left:`${b}px`,right:"inherit",width:`${window.innerWidth}px`})}}};_.Gw.prototype.$wa$Imgh9b=function(){return this.Nc};_.Gw.prototype.$wa$NjCoec=function(){return this.Cb};_.Gw.prototype.$wa$cRhSI=function(){return this.wd};_.Gw.prototype.$wa$k4Iseb=function(){return this.Ub};
_.Gw.prototype.$wa$sQzsob=function(){return this.Nb};_.Gw.prototype.$wa$P9ZzV=function(){return this.Mb};_.Gw.prototype.$wa$TvD9Pc=function(){return this.close};_.Gw.prototype.$wa$tuePCd=function(){return this.YUa};_.Gw.prototype.$wa$sT2f3e=function(){return this.XUa};_.Gw.prototype.$wa$mLt3mc=function(){return this.stopPropagation};_.Gw.prototype.$wa$iWO5td=function(){return this.isOpen};_.Gw.prototype.$wa$AKPITd=function(){return this.rc};_.Gw.prototype.$wa$QYIAte=function(){return this.Rb};
_.Gw.prototype.$wa$FTKt3c=function(){return this.Vb};_.Gw.prototype.$wa$e3lCZb=function(){return this.Qb};_.Gw.prototype.$wa$PobJp=function(){return this.qc};_.Gw.prototype.$wa$HsLDGb=function(){return this.yc};_.Gw.prototype.$wa$Hk83id=function(){return this.Kc};_.Gw.prototype.$wa$Fa4mRc=function(){return this.Jc};_.Gw.prototype.$wa$UxVz5=function(){return this.Lc};_.Yr(_.Ew,_.Gw);
_.u();
_.TsB=_.x("TmFfhf",[_.Xq,_.Pk]);
_.t("TmFfhf");
var UsB=function(a,b){let c;const d=(c=b.getAttribute("data-href"))!=null?c:"";_.yp(a.Tb.oa(),b).log(!0);return d.length>0?(b=new URL(d,window.origin),a.kc.navigateTo(_.bc(b.toString())),!1):!0},VsB=class extends _.Wr{static Sa(){return{service:{kc:_.Vz,Tb:_.Ku}}}constructor(a){super(a.Oa);this.kc=a.service.kc;this.Tb=a.service.Tb}oa(a){if((a=a.targetElement.el())&&a.tagName==="A")return!0;var b;return(b=a.getAttribute("data-href"))!=null&&b?UsB(this,a):(b=a.querySelector("a[data-href]"))?UsB(this,
b):!0}};VsB.prototype.$wa$x8vc1=function(){return this.oa};_.Yr(_.TsB,VsB);
_.u();
_.onC=_.x("jhGntf",[]);
_.t("jhGntf");
var LyG=class extends _.Wr{constructor(a){super(a.Oa);this.oa=!1;this.Ba=_.ol(this.getData("isBilingual"))=="true"}Aa(){this.getRoot().el().hasAttribute("data-enable-pron-promo-always")&&this.getRoot().el().getAttribute("data-enable-pron-promo-always")==="true"||(this.oa||getComputedStyle(this.getRoot().el()).visibility!=="hidden"||(_.Uv([new _.On(this.Ia("MDmfVb").kb(),"show")]),this.oa=!0),_.yl.add(this.getRoot().el(),"Dpxsmd"),this.getRoot().el().setAttribute("aria-hidden","false"),this.Ba?_.yl.add(this.getRoot().el(),
"CXguBb"):_.yl.add(this.getRoot().el(),"ls9hrb"),this.notify("BUYwVb"))}};LyG.prototype.$wa$V46pce=function(){return this.Aa};_.Yr(_.onC,LyG);
_.u();
_.Zle=_.x("Dq2Yjb",[]);
_.t("Dq2Yjb");
_.$le=class extends _.Wr{constructor(a){super(a.Oa);this.Ba=this.oa=this.Aa=this.gU=this.e_=null;this.Ca=!0;this.ARa=this.getData("avo").Lb()}reset(){this.ARa||(this.show(this.e_),this.gU&&this.hide(this.gU),this.hide(this.Aa),this.show(this.oa),this.hide(this.Ba));this.Ca=!0}Da(a){if(!this.Ca)return!0;switch(a.data.playerState){case 6:case 5:case 13:this.hide(this.e_);break;case 9:this.show(this.e_)}if(this.gU)switch(a.data.playerState){case 6:case 5:case 13:this.hide(this.gU);break;case 9:this.hide(this.gU)}var b=
a.data;b.playerState===3&&b.Nqc?this.show(this.Aa):this.hide(this.Aa);a=a.data;a.playerState===9&&this.show(this.oa);a.playerState===4&&this.show(this.oa);a.playerState===3&&a.Nqc&&this.hide(this.oa);a.playerState!==6&&a.playerState!==5&&a.playerState!==13||this.hide(this.oa);return!0}handleError(a){if(this.ARa)return this.hide(this.e_),this.Ca=!1,!0;if(a.data===17)return this.hide(this.e_),this.gU&&this.hide(this.gU),this.hide(this.Aa),this.hide(this.oa),this.hide(this.Ba),!0;this.Ca=!1;this.show(this.e_);
this.gU&&this.hide(this.gU);this.hide(this.Aa);this.hide(this.oa);this.show(this.Ba);return!0}Oc(){this.notify("kPHRVe");this.notify("sZ853b")}show(a){a!==null&&_.Jm(a,!0)}hide(a){a!==null&&_.Jm(a,!1)}};_.$le.prototype.$wa$h5M12e=function(){return this.Oc};_.$le.prototype.$wa$JqRO3d=function(){return this.handleError};_.$le.prototype.$wa$KW0hQe=function(){return this.Da};_.$le.prototype.$wa$S9gUrf=function(){return this.reset};_.ame=function(){};_.Yr(_.Zle,_.$le);
_.ame=(a,b)=>{a.e_===null&&(a.e_=a.Ia("SAtBGf").el());a.e_.textContent="";a.e_.appendChild(b);a.reset()};
_.u();
var dme;dme=_.ee().getDocument().documentElement;_.cme=dme.requestFullscreen?"fullscreenchange":dme.webkitRequestFullscreen?"webkitfullscreenchange":dme.mozRequestFullScreen?"mozfullscreenchange":dme.msRequestFullscreen?"MSFullscreenChange":"fullscreenchange";_.eme=function(){const a=_.ee().getDocument(),b=a.body;return!!(b.webkitRequestFullscreen&&a.webkitFullscreenEnabled||b.mozRequestFullScreen&&a.mozFullScreenEnabled||b.msRequestFullscreen&&a.msFullscreenEnabled||b.requestFullscreen&&a.fullscreenEnabled)};
_.fme=function(a,b){if(a.requestFullscreen)return a.requestFullscreen(b);if(a.webkitRequestFullscreen)return a.webkitRequestFullscreen();if(a.mozRequestFullScreen)return a.mozRequestFullScreen();if(a.msRequestFullscreen)return a.msRequestFullscreen()};_.gme=function(a){a.mozRequestFullScreenWithKeys?a.mozRequestFullScreenWithKeys():_.fme(a)};
_.hme=function(){const a=_.ee().getDocument();a.exitFullscreen?a.exitFullscreen():a.webkitCancelFullScreen?a.webkitCancelFullScreen():a.mozCancelFullScreen?a.mozCancelFullScreen():a.msExitFullscreen&&a.msExitFullscreen()};_.tG=function(){const a=_.ee().getDocument();return!!(a.webkitIsFullScreen||a.mozFullScreen||a.msFullscreenElement||a.fullscreenElement)};
_.bme=_.x("NVlnE",[_.Zle,_.FZa,_.HZa]);
_.t("NVlnE");
var ime=function(a,b=0,c){return{pR:a,lC:b,KZa:c!=null?c:void 0}},jme=function(a,b,c,d,e=!1){a.e_===null&&(a.e_=a.Ia("SAtBGf").el());a.gU===null&&(a.gU=d);a.Aa===null&&(a.Aa=a.Ia("OQ2Y6").el());a.oa===null&&(a.oa=a.Ia("s0D71d").el());a.Ba===null&&(a.Ba=a.Ia("pNdJO").el());d=a.gU?a.gU.style.height:"";e&&a.gU?(a.e_.style.height=d,a.Aa.style.height=d,a.oa.style.height=d,a.Ba.style.height=d):(a.e_.style.removeProperty("height"),a.Aa.style.removeProperty("height"),a.oa.style.removeProperty("height"),a.Ba.style.removeProperty("height"));
a.e_.textContent="";a.e_.appendChild(b);_.Ac(a.Ba,c);a.reset()};var kme={duration:500,easing:"cubic-bezier(0.60, 0.00, 0.00, 1.00)"},lme={duration:500,easing:"cubic-bezier(0.00, 0.00, 1.00, 1.00)"},mme={duration:170,easing:"cubic-bezier(0.00, 0.00, 1.00, 1.00)"},nme={duration:150,easing:"cubic-bezier(0.00, 0.00, 1.00, 1.00)",delay:350},ome=class extends _.mv{constructor(a){super();this.Ba=this.Aa=this.Da=this.Ca=0;this.n2=a.n2;this.DJa=a.DJa;this.g9b=a.g9b;this.f9b=a.f9b;this.e9b=a.e9b;this.fMc=a.fMc;this.gU=a.gU;this.ARa=a.ARa;this.e_=a.e_}measure(){const a=
this.DJa.getBoundingClientRect(),b=this.n2.getBoundingClientRect();this.Ca=a.x-b.x;this.Da=a.y-b.y;this.Aa=a.width/b.width;this.Ba=a.height/b.height}Cc(){this.DJa.style.opacity="0.001"}oa(){const a=_.sv();a.add(_.nv((new _.qv(this.n2,kme)).origin("0 0"),this.Aa,this.Ba,1).Ps(this.Ca,this.Da,0));this.fMc&&this.gU&&(this.gU.style.display="block",a.add((new _.qv(this.gU,kme)).opacity(.001,.999)));this.ARa&&this.e_&&this.e_.parentElement&&(this.e_.parentElement.style.display="block",a.add((new _.qv(this.e_,
lme)).opacity(.999,.001)));this.g9b.forEach(b=>{_.vm(b,"display")!=="none"&&a.add((new _.qv(b,mme)).opacity(.001,.999))});this.f9b.forEach(b=>{_.vm(b,"display")!=="none"&&a.add((new _.qv(b,nme)).opacity(.001,.999))});this.e9b.forEach(b=>{_.vm(b,"display")!=="none"&&a.add((new _.qv(b,nme)).opacity(.001,.999).Ps(0,5,0))});return a.build()}Yi(){return 500}Dh(){this.DJa.style.opacity="";this.n2.style.transform="";this.n2.style.transformOrigin="";this.g9b.forEach(a=>{a.style.opacity=""});this.f9b.forEach(a=>
{a.style.opacity=""});this.e9b.forEach(a=>{a.style.opacity="";a.style.transform="none"})}};var pme={duration:333,easing:"cubic-bezier(.4,0,.2,1)"},qme={duration:350,easing:"cubic-bezier(0.20, 0.00, 0.00, 1.00)"},rme={duration:100,easing:"cubic-bezier(0.20, 0.00, 0.00, 1.00)"},sme={duration:150,easing:"linear",delay:200},tme=function(a){if(!a.Ua&&a.Ya("EyRCvc").size()>0){const b=a.Ab("EyRCvc"),c=a.Ia("GRaaMd").el();_.jf(_.Txc(b.eq(0).el()),()=>{_.tm(c,"display","block");var d=_.sv();d.add((new _.qv(c,nme)).opacity(.001,.999).Ps(0,5,0));d=d.build().play();_.tm(c,"transform","");d.then(()=>
{_.Eq()},()=>{_.Eq()})});a.Ua=!0}},ume=function(a,b,c,d){c=c?{triggerElement:c}:void 0;a.Pg&&a.oa&&c&&(c.data={url:a.oa.Tp()});const e=[];e.push(new _.On(a.getRoot().el(),b));d&&_.Ve(d,"ved")&&e.push(new _.On(d,b));_.Uv(e,c)},vme=function(a,b){return _.Cf(a,c=>c&&c.nodeType===Node.ELEMENT_NODE?_.Ve(c,b):!1,!0,6)},wme=function(a){return _.Cf(a,b=>b&&b.nodeType===Node.ELEMENT_NODE?!!b.getAttribute("href"):!1,!0,5)},yme=function(a,b){a.Cb=!0;b===90||b===270?(a.notify("Lw5Ifc",2),a.Yb&&_.eme()&&!_.tG()&&
(a.rc&&a.Pa(),a.notify("d574Gf"),(b=a.getRoot().el().querySelector("iframe"))?xme(a.Lc?b:a.e0):(b=a.getRoot().el().querySelector("video"))&&xme(b))):(a.notify("Lw5Ifc",1),a.Yb&&_.eme()&&_.tG()&&(a.rc&&a.Pa(),a.notify("DHyZZ"),_.hme()));(_.jla||_.vGa)&&a.play()},xme=function(a){(a=_.fme(a,{navigationUI:"hide"}))&&a.catch(()=>{})},uG=class extends _.Wr{static Sa(){return{controller:{VYe:{jsname:"srpMqc",ctor:_.$le}},service:{PKc:_.t8a,history:_.Y$a}}}constructor(a){super(a.Oa);this.Ha=this.oa=null;
this.Ua=this.Cb=!1;this.Va=this.Wa=null;this.Bb=!1;this.wb=null;this.Lc=!1;this.Ka=1.778;this.Da=!1;this.Na=a.service.PKc;this.Vi=a.service.history;this.Mb=_.Le(_.Iq,this.Fn());this.e0=this.Ia("srpMqc").el();this.gU=this.Ya("UctYzf").el();this.Ld=a.controller.VYe;this.Rb=this.Ia("plIjzf").el();this.Gb=this.Ya("qcQY3").el();this.Ea=this.Ya("HBOHH").el();this.Pd=this.Ya("a6dsU").el();this.wd=this.Ya("gjpz2b").el();this.Ca=this.Ia("gVTuP").el();this.Aa=this.Ya("ni2D0d").el();this.Te=this.Ia("AHe6Kc").el();
this.Ma=this.Ya("Tv8l5d").el();this.Ba=this.Ya("RChmkd").el();this.wg=this.getData("aob").Lb();this.Mc=this.getData("dsktp").Lb();this.qc=this.getData("entl").Lb();this.Yb=this.getData("afor").Lb();this.Pg=this.getData("evfp").Lb();this.ARa=this.getData("avo").Lb();this.Nc=_.ad(this.getData("pmhp"),100);this.Nf=this.getData("evfh").Lb();this.Lf=this.getData("etfb").Lb();this.rc=this.getData("eror").Lb();this.Ta=this.Ya("tXJdKf").el();this.Jc=()=>{this.Cb||document.visibilityState!=="hidden"||this.notify("SUsL8c");
this.Cb=!1};this.Hd=()=>{this.yc()};this.De=()=>{this.Kc()};this.Pa=()=>{this.hb()};this.Na.isAvailable()&&this.Na.l6()?this.Nb=_.Vr(this.Na.back,1E3,this.Na):this.Vi.isAvailable()&&this.Vi.l6()?this.Nb=_.Vr(this.Vi.back,1E3,this.Vi):this.Nb=_.Vr(_.tf,1E3,this);this.jt=this.Mc?null:_.fe(this.getRoot().el(),"scroll",()=>{this.nj()})}nj(){if(this.Ea){var a=this.Ea.getBoundingClientRect();this.getRoot().el().classList.toggle("EKdJIc",a.top-64<0)}}Ub(){_.bn(this.jt)}e$d(a,b){b||(b=this.Ca);this.getRoot().kb().style.display=
"";const c=[this.Rb];this.Pd&&c.push(this.Pd);this.Ea&&c.push(this.Ea);this.Aa&&c.push(this.Aa);this.Gb&&c.push(this.Gb);this.wd&&c.push(this.wd);return new ome({n2:this.e0,DJa:a,g9b:[this.Te],f9b:c,e9b:[b],fMc:this.Da&&(_.zme()>_.Ame()||this.Mc),gU:this.gU?this.gU:void 0,ARa:this.ARa,e_:this.oa?this.oa.NQb:void 0})}hed(){return this.getRoot().kb().style.display==="none"?null:this.wg||this.Ha!==null?(new _.qv(this.getRoot().el(),pme)).opacity(.999,.001):new _.qv(this.getRoot().el(),{duration:0})}Mcd(){this.getRoot().kb().style.opacity=
"";this.getRoot().el().scrollTop=0;this.getRoot().kb().style.display="none";this.Ca&&(this.Ca.style.transform="none");this.Aa&&(this.Aa.style.transform="none");this.Ua&&this.Ya("EyRCvc").size()>0&&(this.Ia("GRaaMd").el().style.opacity="0.0");this.Mb.then(a=>{a&&a.isAvailable()&&a.isInBasicMode()&&a.exitBasicMode(48)})}setContent(a){this.Va=this.Wa=null;this.Bb=!1;this.oa=a;this.Lc=this.oa.iMa().length===0;this.Ka=this.oa.Zn();this.Da=this.Ka<=1;this.hb();this.oa.Nyb&&!this.Mc&&this.Ma&&this.Ma.classList.toggle("euvtE",
this.Ka>=1);this.Ea&&(this.Ea.textContent="",this.Ea.appendChild(a.q1c));this.Ca.textContent="";this.Ca.appendChild(a.Owc);this.Ta&&(this.Ta.textContent="",this.Ta.appendChild(a.T4b));this.Aa&&(this.Aa.textContent="",this.Aa.appendChild(a.Nmc));var b=a.awd;b&&_.Se(this.getRoot().el(),"ved",b);(b=a.Wcd)&&_.Se(this.Rb,"ved",b);this.ARa?_.ame(this.Ld,a.NQb):jme(this.Ld,a.NQb,a.Tp(),this.gU,this.Da);this.Ia("srpMqc").el().classList.toggle("J87uBd",this.Da&&!this.Mc);this.Nf&&!this.Da||this.Aa!==null&&
this.Aa.firstElementChild!==null&&this.Aa.firstElementChild.firstElementChild!==null&&this.Aa.firstElementChild.firstElementChild.childElementCount>0?(this.Ia("srpMqc").addClass("WXyPBc"),this.getRoot().addClass("y15T9c")):(this.Ia("srpMqc").removeClass("WXyPBc"),this.getRoot().removeClass("y15T9c"));this.Mc&&(a=a.wF(),this.Ia("CNzdzb").toggleClass("mTQaif",a),this.Ia("srpMqc").toggleClass("ADu4Ee",a));(a=this.oa.Ygc)&&_.zf(this.e0).appendChild(a)}hb(){if(this.Mc&&!this.Da)this.e0.style.height="",
this.e0.style.width="",this.Ia("srpMqc").removeClass("PGzLDc");else if(!_.Bme()){var a=_.zme(),b=this.Va&&this.Va>a,c=_.zme()>_.Ame(),d=this.Wa!==c;if(this.Mc||this.Wa===null||d||b&&!this.Bb){b&&(this.Bb=!0);this.Wa=c;this.Va=a;b=_.Nm(this.e0).bottom;a=_.Ame();b=_.zme()-b-64;!this.Mc&&this.Da&&c&&this.Nc<100&&(b=Math.round(this.Nc/100*b));d=this.oa&&(c||this.Mc)&&this.Ka>0?this.Ka:1.778;var e=a;var f=Math.round(a/d);this.Mc&&f>b*.67?(f=Math.min(Math.round(b*.67),950),e=Math.round(f*d)):f>b&&(c||(e=
Math.round(b*d)),f=b);this.Ma&&(this.Ma.style.width=`${e}px`);this.Mc&&(this.e0.style.width=`${e}px`,this.Ia("srpMqc").addClass("PGzLDc"));var g;this.Lf&&!this.Mc&&((g=this.oa)==null?void 0:g.Dm())==="TikTok"?_.Cme(this.e0,a,64):this.e0.style.height=`${f}px`;this.gU&&(this.gU.style.height=`${f+64}px`);this.notify("bqsxge")}}}onShow(a,b){this.Ua=!1;_.Nf(this.Ca,"BUYwVb");this.Aa&&_.Nf(this.Aa,"BUYwVb");_.Nf(this.Ca,"tfBUaf");tme(this);this.getRoot().kb().style.display="";this.Qb();this.Vb();ume(this,
"show",a,b);this.Mb.then(c=>{c&&c.isAvailable()&&!c.isInBasicMode()&&c.enterBasicMode(48)});_.Dme()}WU(a){this.vd();this.Dd();this.Ha===null&&a!=null&&_.cma("navigation");this.Ba&&this.notify("Y9mZxe",void 0);if(this.oa){const b=this.oa.Ygc;b&&(_.Jm(b,!1),b.remove())}ume(this,"hide",this.Ha,a);this.Ha=null;this.oa&&this.oa.kFd();this.notify("yV7Gmf");_.Eme();_.Fme(this.Mb)}yrd(a,b,c){this.e0.setAttribute("data-ved",b);this.notify("kPHRVe",{pR:a,dGb:b,KZa:c!=null?c:void 0})}u6a(a,b,c){this.notify("ik7FMc",
ime(a,b,c))}Tkb(a,b,c){this.notify("zX7p1e",ime(a,b,c))}play(){this.notify("sZ853b")}pause(){this.notify("wrZ7db")}stop(){this.notify("QIOTkf")}handleError(a){this.oa&&a.data!==17&&this.oa.F7b();a.data!==9&&a.data!==10||!this.wb||this.wb()}nk(a){a=a.data;_.Gme(_.uf("vld"),a)}uf(a){this.notify("ofUyHd",a.data)}Kf(a){this.notify("qv3l1c",a.data)}zJe(a){this.wb=a}goBack(a){this.Ha=a.qb.el();this.Nb()}vz(a){_.Hme();this.Ha=a.qb.el()}Gg(a){a=_.nm(a.targetElement.el(),"BUTTON")||void 0;this.notify("Y9mZxe",
a)}Jh(){if(!this.oa||!this.oa.Nyb)if(this.notify("Z4zh3b"),this.oa){var a=this.oa.Tp(),b=this.oa.EDd,c=this.Mc?this.Gb:this.Ta||null;b&&c&&(_.Se(c,"ved",b),_.Tke(c,a,b,this.qc))}}Oc(a){var b=_.pl(a.targetElement.getData("hreplace"),""),c=a.targetElement.getData("rv").Lb();b?(a.event.preventDefault(),c||_.Vv(a.targetElement.el()),a=_.jqa(_.Cqa(b).state,"vld"),_.rf("vld",a,!0)):(b=vme(a.targetElement.el(),"time"),c=wme(a.targetElement.el()),!b&&c?this.notify("Mc6zLd"):b&&(c=b,_.Ve(b,"ved")||(c=vme(b,
"ved")||b),_.Ve(c,"ved")&&_.Vv(c),a.event.preventDefault(),a=b?Number(_.Te(b,"time")):0,isNaN(a)&&(a=0),this.notify("bYOBZb",{NUe:a,ePe:!0,lPe:!0})))}zi(){if(this.oa){var a=this.oa.QK(),b=this.oa.zwb();this.notify("KIQFte",{yBa:a,b0a:b})}}Pk(){this.pause()}So(a){if(this.Ba&&this.oa){var b=this.oa.Ygc;if(b){var c=a.data.xT;if(a.data.I5a)if(a=this.Ba.getBoundingClientRect().height,c){var d=this.e0.getBoundingClientRect().height;c=d*.38;d-=c;var e=_.sv();e.add((new _.qv(this.e0,qme)).Xn(.38,.38,1).origin("top left"));
e.build().play();_.tm(b,"width","62vw");_.Jm(b,!0);e=_.sv();e.add((new _.qv(b,sme)).opacity(.001,.999));e.build().play().then(()=>{_.tm(b,"opacity","")});this.notify("FADMgb",{eGb:c+a,K4c:d})}else _.Jm(b,!1),(0,_.Un)(()=>{const f=_.sv();f.add((new _.qv(this.e0,rme)).Xn(1,1,1).origin("0 0"));f.build().play().then(()=>{_.tm(this.e0,"transform","");_.tm(this.e0,"transform-origin","");const g=this.e0.getBoundingClientRect().height;this.notify("FADMgb",{eGb:g,K4c:0})})},50);else c||(_.Jm(b,!1),_.tm(this.e0,
"transform",""),_.tm(this.e0,"transform-origin",""),a=this.e0.getBoundingClientRect().height,this.notify("FADMgb",{eGb:a,K4c:0}))}}}rl(a){if(this.Ba){var b=a.data.xT;a=a.data.I5a;this.getRoot().el().classList.toggle("wcxvLc",b);a?(b?(_.Jm(this.Ba,!0),a=_.sv(),a.add((new _.qv(this.Ba,sme)).opacity(.001,.999)),a.build().play().then(()=>{_.tm(this.Ba,"opacity","")})):_.Jm(this.Ba,!1),a=_.vm(this.Ba,"height"),_.tm(this.e0,"top",b?a:"")):(_.Jm(this.Ba,b),_.tm(this.Ba,"opacity",""),_.tm(this.e0,"top",""))}}Pl(a){this.notify("Z4zh3b");
a=a.targetElement;_.Tke(a.el(),a.el().getAttribute("href"),_.pl(a.getData("ved"),""),this.qc)}Qb(){window.screen.orientation?window.screen.orientation.addEventListener("change",this.Hd):window.addEventListener("orientationchange",this.De);window.addEventListener("resize",this.Pa)}vd(){window.screen.orientation?window.screen.orientation.removeEventListener("change",this.Hd):window.removeEventListener("orientationchange",this.De);window.removeEventListener("resize",this.Pa)}Kc(){const a=window.orientation;
a!==void 0&&yme(this,Math.abs(a))}yc(){screen.orientation&&yme(this,screen.orientation.angle)}Ek(a){this.notify("hqkvNb",a.data)}Vb(){document.addEventListener("visibilitychange",this.Jc)}Dd(){document.removeEventListener("visibilitychange",this.Jc)}Ei(){return this.e0}};uG.prototype.$wa$ALKefc=function(){return this.Ei};uG.prototype.$wa$kMsPqc=function(){return this.Dd};uG.prototype.$wa$jNXoG=function(){return this.Vb};uG.prototype.$wa$khdH1=function(){return this.Ek};uG.prototype.$wa$RrNCYc=function(){return this.yc};
uG.prototype.$wa$RbdvOe=function(){return this.Kc};uG.prototype.$wa$zJNWDe=function(){return this.vd};uG.prototype.$wa$OJxQpd=function(){return this.Qb};uG.prototype.$wa$gH5PY=function(){return this.Pl};uG.prototype.$wa$PsxeLb=function(){return this.rl};uG.prototype.$wa$kbICce=function(){return this.So};uG.prototype.$wa$czz7Xd=function(){return this.Pk};uG.prototype.$wa$q99Cbf=function(){return this.zi};uG.prototype.$wa$h5M12e=function(){return this.Oc};uG.prototype.$wa$zuuSxf=function(){return this.Jh};
uG.prototype.$wa$JPhaPd=function(){return this.Gg};uG.prototype.$wa$pRhyN=function(){return this.vz};uG.prototype.$wa$LNUc7b=function(){return this.goBack};uG.prototype.$wa$LlCODf=function(){return this.Kf};uG.prototype.$wa$GvCSvc=function(){return this.uf};uG.prototype.$wa$g1FFEe=function(){return this.nk};uG.prototype.$wa$JqRO3d=function(){return this.handleError};uG.prototype.$wa$QKiGd=function(){return this.stop};uG.prototype.$wa$HvfI2b=function(){return this.pause};uG.prototype.$wa$NziyQe=function(){return this.play};
uG.prototype.$wa$H29jM=function(){return this.hb};uG.prototype.$wa$T0E1sc=function(){return this.Mcd};uG.prototype.$wa$L7DKxc=function(){return this.hed};uG.prototype.$wa$k4Iseb=function(){return this.Ub};uG.prototype.$wa$Y3U6Wb=function(){return this.nj};_.Bme=function(){return window.innerWidth<document.documentElement.clientWidth};_.Ame=function(){return window.innerWidth};_.zme=function(){return window.innerHeight};_.Hme=function(){_.pf({vld:"",fpstate:""},!1)};_.Gme=function(){};_.Fme=function(){};
_.Dme=function(){};_.Eme=function(){};_.Cme=function(){};_.Yr(_.bme,uG);
_.Pje&&(_.Gme=(a,b)=>{const c=_.ne("l")?_.lf("l",_.eke):null;c&&a&&(isNaN(b)||c.set(a,b))});_.bke&&(_.Ame=()=>_.Bme()?window.innerWidth:document.documentElement.clientWidth,_.zme=()=>_.Bme()?window.innerHeight:document.documentElement.clientHeight);_.cke&&(_.Bme=()=>"visualViewport"in window&&"scale"in window.visualViewport?window.visualViewport.scale!==1:window.innerWidth<document.documentElement.clientWidth);_.Wje&&(_.Cme=(a,b,c)=>{let d,e;((d=window)==null?0:(e=d.CSS)==null?0:e.supports("height","100dvh"))?a.style.height=`min(calc(100dvh - ${c}px), ${1.778*b}px)`:a.style.height=`min(calc(100vh - ${c-80}px), ${1.778*b-c-80}px)`});_.$je&&(_.Dme=()=>{_.P2c(!0)},_.Eme=()=>{_.P2c(!1)});


_.u();
_.Ime=_.x("qmdEUe",[]);
var ile,jle,kle;ile=function(){let a=_.ca;for(;a.parentWindow;)a=a.parentWindow;return a};jle=function(){return ile().youTubeIframeAPILoadingCallbacks};
_.lle=function(){return ile().youTubeIframeAPIInitialized?_.sf(!0):jle()instanceof Array?new _.Df((a,b)=>{jle().push([a,b])}):new _.Df((a,b)=>{_.Eza(ile(),"onYouTubeIframeAPIReady",function(){const c=jle();delete ile().onYouTubeIframeAPIReady;delete ile().youTubeIframeAPILoadingCallbacks;ile().youTubeIframeAPIInitialized=!0;for(const [d]of c)d(!0);a(!0)});_.Eza(ile(),"youTubeIframeAPILoadingCallbacks",[]);_.pF(kle,{timeout:0}).then(null,c=>{const d=jle();b(c);for(const [,e]of d)e(c);delete ile().onYouTubeIframeAPIReady;
delete ile().youTubeIframeAPIInitialized;delete ile().youTubeIframeAPILoadingCallbacks})})};kle=(0,_.ic)`//www.youtube.com/iframe_api?version=3`;
_.t("qmdEUe");
_.Jme=class extends _.bo{constructor(){super();this.oa=new Map}};_.Me(_.Ime,_.Jme);
_.u();
var Lme,Mme,Nme,Pme,Qme;Lme=class extends _.m{constructor(a){super(a)}P5(){return _.wi(this,1)}wUa(){return _.Mg(this,1)}};Mme=class extends _.m{constructor(a){super(a)}};Nme=class extends _.m{constructor(a){super(a)}};_.Ome=class extends _.m{constructor(a){super(a)}};Pme=class extends _.m{constructor(a){super(a)}getType(){return _.wi(this,1)}setType(a){return _.Ig(this,1,a)}Me(){return _.Cj(this,1)}Ie(){return _.Mg(this,1)}};
Qme=class extends _.m{constructor(a){super(a)}getType(){return _.wi(this,2)}setType(a){return _.Ig(this,2,a)}Me(){return _.Cj(this,2)}Ie(){return _.Mg(this,2)}};var Sme,Vme,Wme,ane,dne,ene,fne,Yme,Zme;_.Rme=Date.now;Sme={"cnn.com":1,"ndtv.com":2,"google.com":3};_.Ume=function(a,b){const c=new _.oPb;_.Ig(c,5,2);_.Uf(c,7,b);return new _.Tme(a,c)};Vme=function(){if(window.matchMedia){if(window.matchMedia("(orientation: landscape)").matches)return 2;if(window.matchMedia("(orientation: portrait)").matches)return 1}return 0};Wme=function(a,b,c){a.Ea=Vme();return c!==""?(b.setAttribute("data-ved",c),b):_.Cf(b,d=>d.nodeType!==Node.ELEMENT_NODE?!1:_.Ve(d,"ved"))};
_.$me=function(a,b){a.oa&&(_.Xme()&&Yme(a.Ea||Vme(),a.oa,!1),b&&_.Bb(a.oa,Nme,3,b),Zme(a,a.oa),a.oa=null)};
_.cne=function(a,b,c,d,e=!1){if(a.oa){var f=(0,_.Rme)(),g=_.p(a.oa,_.Ome,1);c&&!_.fd(_.ui(g,4))&&_.bj(g,4,f);switch(b){case 0:_.fd(_.ui(g,1))||_.bj(g,1,f);break;case 1:_.fd(_.ui(g,2))||_.bj(g,2,f);break;case 3:_.fd(_.ui(g,3))||_.bj(g,3,f);break;case 2:_.bj(g,2,f);_.bj(g,3,f);break;case 4:_.fd(_.ui(g,8))||_.bj(g,8,f);break;case 5:case 6:_.bj(g,5,f);_.fd(_.ui(g,8))||_.bj(g,8,f);_.$me(a);break;case 9:case 10:_.$me(a)}}switch(b){case 6:ane(a,d,e);break;case 5:ane(a,d,e,!0);break;case 7:_.bne(a,2,d,!1);
break;case 8:_.bne(a,7,d,!0);break;case 9:case 10:_.bne(a,5,d,!0);break;case 11:_.bne(a,4,d,e);break;case 12:_.bne(a,16,d,e)}};ane=function(a,b,c,d=!1){a.Aa||(dne(a,b),b=d?1:2,c&&(b=3),c=_.p(a.Ba,Qme,2),_.Xi(c,2)!==b&&_.bg(c,Pme,3,_.cg()).length&&ene(a),c.setType(b))};_.bne=function(a,b,c,d,e=0){const f=_.p(a.Ba,Qme,2);var g=_.bg(f,Pme,3,_.cg()).length;a.Aa?fne(a,b,c):g&&e>0&&(g=_.bg(f,Pme,3,_.cg())[g-1],_.ld(_.ni(g,4))+e>c&&_.Ig(g,2,b));d&&_.bg(f,Pme,3,_.cg()).length!==0&&ene(a)};
dne=function(a,b){a.Aa=new Pme;_.zg(a.Aa,3,b)};ene=function(a,b){b&&_.Bb(a.Ba,Nme,3,b);Zme(a,a.Ba);b=_.p(a.Ba,Qme,2);_.Kd(b,3);_.Kd(a.Ba,3)};fne=function(a,b,c){if(a.Aa){const d=_.p(a.Ba,Qme,2);_.Ig(a.Aa,2,b);_.zg(a.Aa,4,c);_.qh(d,3,Pme,a.Aa);a.Aa=null}};_.gne=function(a,b,c){const d=!!a.Aa;a.Aa||dne(a,b);fne(a,c,b);d&&dne(a,b)};Yme=function(a,b,c=!1){const d=new Mme,e=new Lme;var f=(0,_.Rme)();_.bj(e,2,f);_.Kg(e,3,c);_.Ig(e,1,a);_.qh(d,3,Lme,e);_.Bb(b,Mme,9,d)};
Zme=function(a,b){b=_.Cd(b.Aa(),4);_.hne(b);_.Vv(a.Da,{userAction:1,data:{vwd:b}})};_.ine=function(a,b,c=!1){const d=a.Ca.clone();Yme(b,d,c);Zme(a,d)};_.jne=function(a,b,c){a.Aa&&fne(a,12,c);c=0;switch(b){case 1:c=34;break;case 2:c=35;break;case 3:c=33;break;case 4:c=1;break;case 5:c=35;break;case 6:c=3;break;case 7:c=35;break;case 8:c=1;break;case 9:c=15;break;case 10:c=18;break;case 11:c=37;break;case 16:c=40;break;case 12:c=38;break;case 13:c=39;break;case 15:c=41;break;case 14:c=42}a.logError(c)};
_.kne=function(a,b){a.logError(36);_.Vv(b,{userAction:1})};
_.Tme=class{constructor(a,b,c=""){this.Ca=b;this.Aa=this.Ea=this.oa=null;this.Da=Wme(this,a,c);a=this.Ba=this.Ca.clone();b=new Qme;_.Bb(a,Qme,2,b);this.reset()}update(a,b,c=""){this.Da=Wme(this,a,c);b.id&&_.Uf(this.Ca,6,b.id);if(b.url){_.Uf(this.Ca,7,b.Aha);a=b.publisher;b=0;if(a)for(const d of Object.keys(Sme))if(_.naa(d,a.slice(a.length-d.length))==0){b=Sme[d];break}_.Ig(this.Ca,11,b)}}reset(){var a=null;this.oa&&(a=_.p(this.oa,_.Ome,1));var b=this.oa=this.Ca.clone();a=a?a:new _.Ome;_.Bb(b,_.Ome,
1,a);b=this.Ba=this.Ca.clone();a=new Qme;_.Bb(b,Qme,2,a);this.Aa=null}logError(a){var b=new Nme;a=_.Ig(b,1,a);a=_.Kg(a,3,!1);this.oa?_.$me(this,a):ene(this,a)}};_.hne=function(){};_.Xme=function(){return!1};
_.Xme=()=>!0;
_.Kme=_.x("UqGwg",[_.Ime,_.Gq]);
_.t("UqGwg");
var mne=function(a,b,c){const d={events:{onReady:()=>{a(e)}}};typeof c==="string"&&c.length>0&&(d.embedConfig={enc:c});const e=new YT.Player(b,d)},nne=function(a){const {tLb:b,style:c,languageCode:d="",DBa:e}=a;a=_.Yl("IFRAME");a.setAttribute("allowfullscreen",b?"1":"0");a.setAttribute("allow",b?"accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope":"autoplay; clipboard-write; encrypted-media");a.setAttribute("frameborder","0");a.setAttribute("width","100%");a.setAttribute("height",
"100%");a.setAttribute("referrerpolicy","unsafe-url");a.setAttribute("style",c);try{var f=(0,_.ic)`https://www.youtube.com/embed/?enablejsapi=1&rel=0&autoplay=0&playsinline=1&fs=${b?"1":"0"}&hl=${d}`;if(typeof e==="string"&&e.length>0){const g=JSON.stringify({enc:e});f=(0,_.ic)`https://www.youtube.com/embed/?enablejsapi=1&rel=0&autoplay=0&playsinline=1&fs=${b?"1":"0"}&hl=${d}&embed_config=${g}`}_.Bc(a,f)}catch(g){f=(0,_.ic)`https://www.youtube.com/embed/?enablejsapi=1&rel=0&autoplay=0&playsinline=1&fs=0&hl=${d}`,
typeof e==="string"&&e.length>0&&(f=JSON.stringify({enc:e}),f=(0,_.ic)`https://www.youtube.com/embed/?enablejsapi=1&rel=0&autoplay=0&playsinline=1&fs=0&hl=${d}&embed_config=${f}`),_.Bc(a,f)}return a},one=function(a){let {vC:b,iframe:c,iYb:d,tLb:e,style:f,languageCode:g,DBa:h}=a;c||(c=nne({tLb:e,style:f,languageCode:g,DBa:h}));return new _.Df((k,l)=>{_.lle().then(()=>{b.contains(c)||b.appendChild(c);c&&mne(k,c,h)},n=>{d===0?one(Object.assign({},a,{iYb:-1})).then(k,l):d>0?(0,_.Un)(()=>{one(Object.assign({},
a,{iYb:-1})).then(k,l)},d):l(n)})})},pne=function(a,b){b.textContent="";const c=a.oa.get(b);c&&(a.oa.delete(b),c.then(d=>{d.destroy()},()=>{}))},qne=function(a,b){const c=b.vC;b=one(b);a.oa.set(c,b);return b},rne=function(a){if(a.oa&&_.Qh(a.oa,_.Ome,1)){var b=_.p(a.oa,_.Ome,1);_.WBa(b,9)!=null&&_.$me(a)}},sne=function(a){const b=new _.oPb;_.Ig(b,5,1);_.Uf(b,6,"undefined");return new _.Tme(a,b,"")},tne=function(a){a.Wn=!0;a.Qb=_.qe();a.Ka=_.qe();a.Ca=null;a.Wa=null;rne(a.oa);a.oa.reset();a.Na=!1;a.Pa=
!1},vG=function(a,b,c=0,d=!1){a.Pf=b;a.trigger("aWkxge",{playerState:b,Nqc:a.Aa,ajc:c});b===7&&a.Ba>0&&(c<a.Ba||c>a.Ba+1)&&Date.now()-a.Cb<1E3?_.cne(a.oa,b,a.Aa,Math.round(a.Ba*1E3),d):_.cne(a.oa,b,a.Aa,c,d)},xne=function(a,b){if(b&&b.pR){const d=b.pR.id||null;a.Ua&&(a.oa=sne(a.n2));a.oa.update(a.n2,{id:d||"test"},b.dGb);a.videoId!==d?tne(a):a.oa.reset();a.Ha&&(a.videoId=d,vG(a,0));a.wb&&vG(a,1)}if(!a.Ha){vG(a,0);a.Ha=!0;var c;qne(a.Tqc,{vC:a.n2,iframe:a.Ua,iYb:a.iYb,tLb:a.tLb,languageCode:a.languageCode,
DBa:b==null?void 0:(c=b.pR)==null?void 0:c.DBa}).then(d=>{d.getIframe()&&d.getIframe().removeAttribute("title");a.player=d;a.player.addEventListener("onError",e=>{if(e&&e.data!==a.Wa){a.Ea=!1;a.Wa=e.data?e.data:null;var f=0;switch(e.data){case 2:f=1;break;case 5:f=2;break;case 100:f=3;break;case 101:case 150:f=4}a.trigger("sCmk",f);e=une(e);_.jne(a.oa,f,e)}});a.player.addEventListener("onStateChange",e=>{e&&e.target&&vne(a,e.target,e.data,!1)});a.player.addEventListener("onApiChange",()=>{a.Wn||a.Qb.resolve()});
a.player.addEventListener("onAdStateChange",e=>{e&&e.target&&vne(a,e.target,e.data,!0)});a.player.addEventListener("onAutoplayBlocked",()=>{a.Ea=!1;if(a.De&&!a.Bb)a.Bb=!0,a.Gb(),a.Ka.resolve(a.player),wne(a);else{const e=a.Ia("WZfLne").el();_.kne(a.oa,e);a.trigger("sCmk",17);a.Na=!1;a.Wn=!1}});a.player.addEventListener("onVideoProgress",e=>{e&&(e=e.data,a.trigger("mUeCJd",e),a.Ba>0&&(e<a.Ba||e>a.Ba+1)&&Date.now()-a.Cb<1E3&&_.bne(a.oa,3,Math.round(a.Ba*1E3),!1,200),a.Ba=e,a.Cb=Date.now())});a.player.addEventListener("SEEK_TO",
e=>{e&&a.trigger("Yr8W2b",e.data)});a.wb=!0;vG(a,1);a.Ma.resolve(d)},()=>{a.trigger("sCmk",9);_.jne(a.oa,9,0);a.hb()})}},yne=function(a,b,c){return c?{startSeconds:b,videoId:a,embedConfig:{zVf:c}}:{startSeconds:b,videoId:a}},zne=function(a,b,c=!1){c&&(a=a.aspectRatio<=1,b.setCenterCrop instanceof Function&&a?b.setCenterCrop(!0):b.setCenterCrop instanceof Function&&b.setCenterCrop(!1))},Ane=function(a,b){a.Va=!1;a.Aa=!0;let c=0;if(b&&b.pR){const d=b.pR.id;a.aspectRatio=b.pR.aspectRatio||1.778;c=b.lC?
b.lC:0;d&&d!==a.videoId&&(a.videoId&&tne(a),a.videoId=d)}a.videoId&&(a.Wn?a.Na||(a.Na=!0,a.Ma.promise.then(d=>{vG(a,3);if(a.videoId)try{let e;const f=yne(a.videoId,c,b==null?void 0:(e=b.pR)==null?void 0:e.DBa);a.player.loadVideoById(f);a.Ea=!0;zne(a,d,a.Mc)}catch(e){a.trigger("sCmk",10),_.jne(a.oa,10,0),a.hb()}})):a.Ma.promise.then(d=>{d.seekTo(c);d.playVideo()}))},Bne=function(a){a.Rb>4&&a.player.wakeUpControls instanceof Function&&a.player.wakeUpControls()},Cne=function(a){a.Ta&&((0,_.Xn)(a.Ta),
a.Ta=null)},wne=function(a){a.Da&&((0,_.Vn)(a.Da),a.Da=null);Cne(a);Bne(a);a.Ta=(0,_.Wn)(()=>{a.player.isMuted()?Bne(a):(a.Nb(),Cne(a),a.Da&&((0,_.Vn)(a.Da),a.Da=null))},1E3);a.Da=(0,_.Un)(()=>{Cne(a)},a.Rb*1E3)},une=function(a){if(!a)return-1;a=a.target||a;return a.getCurrentTime?Math.trunc(a.getCurrentTime()*1E3):-1},vne=function(a,b,c,d=!1){c===YT.PlayerState.PLAYING&&a.n2.getBoundingClientRect().width===0&&b&&b.pauseVideo();if(!a.Va)switch(c===YT.PlayerState.BUFFERING&&(a.Pa=!0),c===YT.PlayerState.PLAYING&&
(a.Wn&&(a.Wn=!1),a.Ka.resolve(b)),c){case YT.PlayerState.PLAYING:if(!a.Ea||a.Pa)a.n2.style.display="block",c=b.isMuted()?5:6,vG(a,c,une(b),d);break;case YT.PlayerState.PAUSED:a.Ea&&!a.Pa||vG(a,7,une(b),d);break;case YT.PlayerState.ENDED:vG(a,11,une(b),d)}},Dne=async function(a,b){try{const c=b.data.ePe,d=b.data.lPe,e=b.data.NUe,f=_.y(await _.y(a.Ka.promise)),g=une(f);vG(a,7,g);d&&f.wakeUpControls instanceof Function&&f.wakeUpControls();f.seekTo(e,!0);c&&a.Mb()}finally{_.y()}},Ene=async function(a,
b){try{if(a.Ca)a.Ca=b;else{a.Ca=b;var c=_.y(await _.y(a.Ka.promise));a.Ca&&(a.Ca(c),a.Ca=null)}}finally{_.y()}},wG=class extends _.Wr{static Sa(){return{service:{Tqc:_.Jme,Ac:_.iv}}}constructor(a){super(a.Oa);this.Pa=this.Na=this.wb=this.Ha=!1;this.aspectRatio=1.778;this.Wn=!0;this.Cb=this.Ba=0;this.Ca=this.player=this.Ta=this.Da=null;this.Va=!1;this.Wa=null;this.Bb=this.Aa=!1;this.Ac=a.service.Ac;const b=this.getData("vid");this.Ua=this.Ya("vLxpee").el();this.videoId=b.Lb()?_.ll(b):null;this.tLb=
this.getData("efs").Lb();this.Mc=this.getData("dsktp").Lb();this.iYb=this.getData("rifd").Lb()?_.ul(this.getData("rifd")):-1;this.Ea=!0;this.De=this.Jhb();this.Rb=_.ad(this.getData("scoab"),4);this.Tqc=a.service.Tqc;this.n2=this.Ia("FPqwbd").el();this.languageCode=_.pl(this.getData("lang"),"");this.Qb=_.qe();this.Ka=_.qe();this.Ma=_.qe();this.oa=this.Ua?null:sne(this.n2);this.Pf=0}Dd(){}Jc(a){xne(this,a.data)}Te(a){if(a.data.pR.id){const b=a.data.lC?a.data.lC:0;this.videoId=a.data.pR.id;this.aspectRatio=
a.data.pR.aspectRatio||1.778;this.Ma.promise.then(c=>{try{c.preloadVideoByPlayerVars(yne(a.data.pR.id,b,a.data.pR.DBa));zne(this,c,this.Mc);var d=this.oa;if(d.oa){var e=(0,_.Rme)(),f=_.p(d.oa,_.Ome,1);_.fd(_.ui(f,9))||_.bj(f,9,e)}}catch(g){this.trigger("sCmk",10),_.jne(this.oa,10,0)}})}}Kc(a){Ane(this,a.data)}hb(){this.Ha&&(vG(this,9,une(this.player)),pne(this.Tqc,this.n2),this.wb=this.Ha=!1,this.Ma=_.qe(),tne(this))}Jhb(){return _.hv(this.Ac).split("&").includes("ibp=video")}seek(a){Dne(this,a)}Gb(){this.Aa=
!0;vG(this,this.Pf);Ene(this,this.Ld)}Ld(a){a.mute();a.playVideo()}play(){this.Aa=!0;vG(this,this.Pf);Ene(this,this.Nc)}Nc(a){a.unMute();a.playVideo()}Mb(){this.Aa=!0;vG(this,this.Pf);Ene(this,this.Pd)}Pd(a){a.playVideo()}pause(){this.Aa=!1;vG(this,this.Pf);Ene(this,this.Hd)}Hd(a){a.pauseVideo()}stop(){this.Bb=this.Aa=!1;vG(this,this.Pf);Ene(this,this.vd);Cne(this)}vd(a){this.Va=!0;this.Ea?(a.pauseVideo(),rne(this.oa),this.oa.reset()):(a.stopVideo(),tne(this))}Lc(){vG(this,10,une(this.player))}Vb(){var a=
this.oa,b=une(this.player);_.bne(a,11,b,!0)}wd(){var a=this.oa,b=une(this.player);_.bne(a,19,b,!0)}yc(){const a=Math.trunc(une(this.player));this.trigger("wdB15",Math.trunc(a/1E3));_.bne(this.oa,6,a,!0)}rc(){const a=une(this.player);_.gne(this.oa,a,9)}qc(){const a=une(this.player);_.gne(this.oa,a,18)}Nb(){const a=une(this.player);_.gne(this.oa,a,20)}Yb(a){this.player&&_.ine(this.oa,a.data)}};wG.prototype.$wa$felZtc=function(){return this.Yb};wG.prototype.$wa$p3OAob=function(){return this.Nb};
wG.prototype.$wa$q1D8lc=function(){return this.qc};wG.prototype.$wa$GK6dXc=function(){return this.rc};wG.prototype.$wa$h8mX4=function(){return this.yc};wG.prototype.$wa$rteA8d=function(){return this.wd};wG.prototype.$wa$xwNlv=function(){return this.Vb};wG.prototype.$wa$L2yHvb=function(){return this.Lc};wG.prototype.$wa$QKiGd=function(){return this.stop};wG.prototype.$wa$HvfI2b=function(){return this.pause};wG.prototype.$wa$pKXSId=function(){return this.Mb};wG.prototype.$wa$NziyQe=function(){return this.play};
wG.prototype.$wa$EcoM8e=function(){return this.Gb};wG.prototype.$wa$QXm1Ib=function(){return this.seek};wG.prototype.$wa$nAl5bb=function(){return this.hb};wG.prototype.$wa$c8EXw=function(){return this.Kc};wG.prototype.$wa$oZx48=function(){return this.Te};wG.prototype.$wa$ZLRSBf=function(){return this.Jc};wG.prototype.$wa$JZXyEc=function(){return this.Dd};_.Yr(_.Kme,wG);
_.u();
_.t("hezEbd");
_.BtF=class extends _.tw{constructor(a){super(a.Oa)}eAe(a,b){_.ds(this).measure(c=>{const d=this.getElementToFocus(a,b);d&&(c.GJ=d)}).Cc(c=>{c.GJ&&this.Aa(c.GJ)}).build()()}getElementToFocus(a,b){return _.ZOa(_.KSb(this,a),c=>c.equals(b)).isEmpty()?_.nw(this,a).first():b}Aa(a){a.focus({preventScroll:!0})}};_.Me(_.p0a,_.BtF);
_.u();
_.OEr=_.x("qcH9Lc",[_.Hw]);
_.t("qcH9Lc");
var PEr=class extends _.m{constructor(a){super(a)}Na(){return _.rd(this,1)}Bb(){return _.pd(this,1)}Aa(){return _.z(this,6)}Pa(){return _.sj(this,6)}Ma(){return _.A(this,2)}wb(){return _.zj(this,2)}Ka(){return _.A(this,3)}hb(){return _.zj(this,3)}Ba(){return _.A(this,4)}Ta(){return _.zj(this,4)}Ha(){return _.A(this,7)}Wa(){return _.zj(this,7)}Da(){return _.z(this,8)}Va(){return _.sj(this,8)}Ca(){return _.z(this,9)}Ua(){return _.sj(this,9)}};PEr.prototype.ob="z6bOeb";var QEr=class extends _.Wr{static Sa(){return{jsdata:{IMe:PEr},controllers:{Pwc:{jsname:"sJmFhc",ctor:_.Jw},mBe:{jsname:"BDbGbf",ctor:_.gg}}}}constructor(a){super(a.Oa);this.MVc=a.jsdata.IMe||null;this.oa=a.controllers.mBe[0]||null;this.jf=a.controllers.Pwc[0]||null}Ba(a){_.Vv(a.qb.el());a=this.eT(a.qb.el(),_.ad(a.qb.getData("biw"),0));this.jf.Ka(a);this.logVisibility(!0)}openModal(a){_.Vv(a.qb.el());this.eT(a.qb.el(),_.ad(this.Ia("gXWYVe").getData("biw"),0));this.oa.open();this.logVisibility(!0)}close(){let a;
(a=this.oa)==null||a.close();let b;(b=this.jf)==null||b.close();this.logVisibility(!1)}closeModal(){this.oa.close();this.logVisibility(!1)}Aa(){this.jf.close();this.logVisibility(!1)}logVisibility(a){_.Uv([new _.On(this.Ia("C8RmQc").el(),a?"show":"hide")])}eT(a,b){a=new Map;if(this.MVc){const c=new _.Sd("/");a=this.MVc;let d;d=new _.Tv(c.searchParams,a);_.Rv(d,a.Bb,a.Na,"lstsd");_.Sv(d,a.Pa,a.Aa,"lstjm");_.Qv(d,a.wb,a.Ma,"lsts2b");_.Qv(d,a.hb,a.Ka,"lsts2c");_.Qv(d,a.Ta,a.Ba,"lsthwfi");_.Qv(d,a.Wa,
a.Ha,"lsls");_.Sv(d,a.Va,a.Da,"lselq");_.Sv(d,a.Ua,a.Ca,"lsapr");a=new Map(c.searchParams)}a.set("biw",b);return _.Txc(this.Ia("C8RmQc").el(),{urlParams:a})}};QEr.prototype.$wa$b6DXXd=function(){return this.Aa};QEr.prototype.$wa$CEnhyd=function(){return this.closeModal};QEr.prototype.$wa$TvD9Pc=function(){return this.close};QEr.prototype.$wa$HTIlC=function(){return this.openModal};QEr.prototype.$wa$A8dlQd=function(){return this.Ba};_.Yr(_.OEr,QEr);

_.u();
_.t("pjDTFb");
var bCr;bCr=function(a,b){const c=new _.Sd(a.Ac.toString());"devloc dlhwsrc dlhwtype dlnr dlta sei stick ved".split(" ").forEach(d=>{c.searchParams.delete(d)});b.forEach((d,e)=>{d?c.searchParams.set(e,d):c.searchParams.delete(e)});return c};_.cCr=class extends _.bo{static Sa(){return{service:{Ac:_.iv}}}constructor(a){super();this.Ac=a.service.Ac}oa(a){return _.bc(bCr(this,a).toString())}};_.Me(_.aCr,_.cCr);
_.u();
_.t("gCngrf");
_.JBr=async function(a,b,c,d,e){try{d&&(a.oa=!0,_.Ig(a.Aa,4,1)),e&&(a.oa=!0,_.Ig(a.Aa,4,_.GAr(e))),a.oa=!0,_.aj(a.Aa,5,b),_.bBr(a,c),_.y(await _.y(a.flush()))}finally{_.y()}};_.KBr=function(a){if(a===null)return 0;switch(a){case "granted":return 2;case "denied":return 3;case "prompt":return 1;default:return 0}};

_.u();
_.dCr=_.x("sA1ssc",[_.aCr]);
_.cVh=class extends _.m{constructor(a){super(a)}};_.cVh.prototype.ob="ITZAN";
_.t("sA1ssc");
var eCr=function(a,b){const c=_.HBr();return b.VEc===0?c.getCurrentPosition(a,b.B4):(new _.$Ar(c)).getCurrentPosition(a,b.VEc)},fCr=async function(a,b,c,d){try{const f=new _.cBr(c),g=_.zBr(b,f);_.y(await _.y(g.bYa()));try{const h=_.y(await _.y(eCr(a,d)));_.y(await _.y(g.FFb()));a=g;var e=h.WBd;(e?e===2:a.T4a())&&_.bBr(f,!0);_.y(await _.y(f.flush()));return h.aNb}catch(h){_.y();const k=_.WAr(h);_.y(await _.y(g.EFb(k)));const l=!k.oa();g.T4a()&&_.bBr(f,l);_.y(await _.y(f.flush()));_.y(await _.y(g.Ba()));
throw new _.B0(k.code,k.message);}}finally{_.y()}},gCr=async function(a,b,c,d,e){try{const k=new _.cBr(d);k.oa=!0;_.Ig(k.Aa,7,4);_.aBr(k,a.QTc);c=k;var f=a.MTc;c.oa=!0;var g=c.Aa,h=_.FAr(f);_.Ig(g,14,h);try{const l=_.y(await _.y(eCr(b,e)));_.y(await _.y(_.JBr(k,a.wPa,!0,!0)));return l.aNb}catch(l){_.y();const n=_.WAr(l);_.y(await _.y(_.JBr(k,a.wPa,!n.oa(),!1,n.code)));throw new _.B0(n.code,n.message);}}finally{_.y()}},iCr=async function(a,b,c=hCr,d){try{try{const e=_.y(await _.y(d(3,a,b,c)));(new _.ZAr(!1,
!0)).write(e,a);return e}catch(e){throw _.y(),_.WAr(e).oa()&&_.AAr(),e;}}finally{_.y()}},jCr=async function(a,b,c=hCr){return iCr(a,b,c,fCr)},kCr=async function(a,b,c,d=hCr){c=gCr.bind(null,c);return iCr(a,b,d,c)},lCr=function(){let a=0;_.wBr&&(a=1);_.tBr&&(a=3);_.xBr&&(a=2);return{B4:3E4,VEc:a}},hCr={B4:3E4,VEc:0},mCr=function(a,b,c,d,e){c={QTc:_.JAr(_.KBr(c)),MTc:_.JAr(_.KBr(d)),wPa:e};return kCr(a.oa,b,c,lCr())},nCr=class{constructor(a){this.oa=a}},oCr=function(a,b){_.BSb();b=b instanceof _.B0?
b:null;const c=b!==null&&b.oa();a.Aa||!c?a.fub.xZb(b):a.Ha.xZb(b)},rCr=function(a,b,c){b.event.stopPropagation&&b.event.stopPropagation();if(a.disabled)return b.event.preventDefault&&b.event.preventDefault(),Promise.resolve();pCr(a,!0);_.Nf(document,"M5Bnof",{YSc:a.YSc});a.Aa||_.vd(c)&&_.Vv(c);return qCr(a,!0)},pCr=function(a,b){a.disabled!==b&&(a.disabled=b,a.Ma&&a.Ma.setAttribute("disabled",String(b)))},qCr=async function(a,b){try{a.Ea();a.Ka();try{const c=_.y(await _.y(a.Aa&&a.oa!==null?mCr(a.Da,
a.oa.kL,a.oa.initialPermissionStatus||null,a.oa.permissionStatus||null,a.oa.wPa):jCr(a.Da.oa,a.root,lCr())));if(b){const d=new Map([["dlnr","1"]]);a.Ba&&d.set("ved",a.Ba);a.Ca&&d.set("q",a.Ca);const e=new Map([["lat",c.coords.latitude],["lng",c.coords.longitude],["radius",c.coords.accuracy]]);pCr(a,!1);_.y(await _.y((0,_.re)(()=>{a.zCb.dismiss()})));a.trigger("gfszqc",{parameters:d,gbe:e})}else{const d=new Map([["sei",_.pla(a.root)],["dlnr","1"]]);a.Ba&&d.set("ved",a.Ba);a.reload(d)}}catch(c){if(_.y(),
pCr(a,!1),oCr(a,c),a.oa!==null){const d=Object.assign({},a.oa,{error:c});a.notify("La2psd",d);a.trigger("La2psd",d)}else a.notify("x8GQkd",c),a.trigger("x8GQkd",c)}}finally{_.y()}},sCr=class extends _.Wr{static Sa(){return{controllers:{AWe:{jsname:"nw18gf",ctor:_.gg}},controller:{fub:{jsname:"Nf9Im",ctor:_.gg},zCb:{jsname:"M8d6me",ctor:_.gg}},service:{Doa:_.cCr},jsdata:{r2c:_.cVh}}}constructor(a){super(a.Oa);this.root=this.getRoot().el();const b=this.Ya("Fz56Ue");this.Ba=b.isEmpty()?null:_.vd(b.el());
this.Ma=this.Ya("O7E8xe").el();this.Doa=a.service.Doa;this.zCb=a.controller.zCb;this.fub=a.controller.fub;this.Ha=a.controllers.AWe[0]||this.fub;a=a.jsdata.r2c;this.Ca=_.A(a,9);this.Da=new nCr(_.wi(a,3));this.YSc=_.wi(a,11);this.Aa=this.disabled=!1;this.oa=null;_.pl(this.getRoot().getData("initiallyHidden"),"")==="1"&&_.vm(this.root,"display")!=="none"&&_.Uv([new _.On(this.root,"show")])}Ea(){this.Ha.wjc()}Pa(a){this.Aa=!0;this.oa=a.data;return rCr(this,a,a.qb.el())}Ta(a){this.Aa=!1;this.oa=null;
return rCr(this,a,a.qb.el())}Na(){return qCr(this,!1)}Ua(a){a=!!a&&a.data||{};this.reload(a.parameters,a.nEc)}reload(a,b=!1){const c=this.Doa.oa(a);(0,_.re)(()=>{pCr(this,!1);this.zCb.dismiss();this.notify("D7JhZd",{url:c,nEc:b})})}Ka(){this.zCb.setTimeout(45E3);this.zCb.show()}};sCr.prototype.$wa$AcH2Mc=function(){return this.Ka};sCr.prototype.$wa$b4F0De=function(){return this.Ua};sCr.prototype.$wa$mHiIrb=function(){return this.Na};sCr.prototype.$wa$T1dibd=function(){return this.Ta};
sCr.prototype.$wa$nPH0X=function(){return this.Pa};sCr.prototype.$wa$s6rKT=function(){return this.Ea};_.Yr(_.dCr,sCr);
_.u();
_.YBr=_.x("khkNpe",[_.Xq]);
_.t("khkNpe");
_.ZBr=class extends _.Wr{static Sa(){return{controller:{Kj:{jsname:"Ng57nc",ctor:_.gg}},service:{kc:_.Vz}}}constructor(a){super(a.Oa);this.kc=a.service.kc;this.Kj=a.controller.Kj}setTimeout(){this.Kj.setTimeout(null)}show(){this.Kj.show()}wjc(){}xZb(){this.setTimeout();this.show()}oa(){var a=this.Ia("zrfavf").el();_.vd(a)&&_.Vv(a);a="//support.google.com/websearch";a=_.Rg(this.getRoot().getData("linkToTop"),!1)?a+"/answer/179386?":a+"?p=refresh_location&";a+="hl=en";const b=_.ad(_.Zc("QrtxK"),0);
b>0&&(a+="&authuser="+b);a=_.bc(a);_.Rg(this.getRoot().getData("openInNewTab"),!1)?_.Cc(this.getWindow(),a,"_blank"):this.kc.navigateTo(a)}};_.ZBr.prototype.$wa$No7Jhf=function(){return this.oa};_.ZBr.prototype.$wa$OMGAsb=function(){return this.wjc};_.ZBr.prototype.$wa$ti6hGc=function(){return this.show};_.ZBr.prototype.$wa$GnCETb=function(){return this.setTimeout};_.Yr(_.YBr,_.ZBr);
_.u();
});
// Google Inc.
