loaded_h_0(function(_){var window=this;
_.ZSb=function(a){var b=new _.YSb;return _.Ig(b,1,a)};_.$Sb=function(a,b){return _.Ig(a,2,b)};_.aTb=function(a,b){return _.Kg(a,5,b)};_.bTb=function(a,b){return _.Kg(a,6,b)};_.cTb=function(a,b){return _.Kg(a,7,b)};_.dTb=function(a,b){return _.Kg(a,8,b)};_.eTb=function(a,b){return _.Kg(a,9,b)};_.fTb=function(a,b){return _.Kg(a,10,b)};_.gTb=function(a,b){return _.Kg(a,11,b)};_.hTb=function(a,b){return _.Kg(a,12,b)};_.iTb=function(a,b){return _.Kg(a,13,b)};_.jTb=function(a,b){return _.Kg(a,14,b)};
_.kTb=function(a,b){return _.Kg(a,15,b)};_.lTb=function(a,b){return _.Kg(a,16,b)};_.YSb=class extends _.m{constructor(a){super(a)}};_.YSb.prototype.ob="mVjAjf";
_.vw=_.x("DPreE",[_.Sq,_.Uq]);
_.t("DPreE");
var qTb;qTb=function(a){let b=8;switch(a){case 2:b=2;break;case 1:b=8;break;case 3:b=12;break;case 5:b=3;break;case 4:b=9;break;case 6:b=13}return b};
_.xw=class extends _.Wr{static Sa(){return{jsdata:{Rhe:_.YSb},service:{dismiss:_.gw,yq:_.lv}}}constructor(a){super(a.Oa);this.Mc=_.Zc("LVIXXb").Ug(_.Oo,1)===1;this.Aa=1;this.offsetY=this.offsetX=0;this.Na=this.Pa=this.Ka=!1;this.data=a.jsdata.Rhe;this.Ba=a.service.dismiss;this.yq=a.service.yq;this.root=this.getRoot().el();this.popup=this.Ia("V68bde").kb();_.zo(this,this.popup);this.Ma=()=>{this.reposition()};_.fe(window,"resize",this.Ma);this.Ta=this.oa().hasAttribute("role");this.Pa=_.z(this.data,
13);this.Na=_.z(this.data,14);this.Ha()}Ub(){this.Ea()&&this.isVisible()?this.Ba.dismiss(this.popup):this.Ba.unlisten(this.popup);_.$m(window,"resize",this.Ma);_.Of(this.root,this.popup)||this.root.appendChild(this.popup);super.Ub()}onDismiss(a,b,c=null){if(c&&_.af(c)&&c.nodeType>0&&_.Of(this.oa(),c)||a.some(d=>_.Of(d,c)))return!1;if(_.z(this.data,12))return this.trigger("al5F3e",{type:b,Tw:c}),!0;this.setVisible(!1);_.Nf(document,"al5F3e");if(b===2||_.z(this.data,16))a=this.oa(),a.hasAttribute("tabindex")||
(a=a.firstElementChild),a.focus();this.Aa=1;return!0}qk(a){var b=a.event;if(!b)return!1;b=b.which||b.keyCode;b!==40&&b!==38||!this.getPopup().querySelector("g-menu")||(this.yq.disable(),this.Ca(a),(0,_.Un)(()=>{this.yq.enable()},0));return this.Na}Va(a){var b=this.Ab("XPtOyb").toArray();a=a.event;if(!a)return!1;const c=a.key;if(c==="ArrowRight"||c==="ArrowDown"){a.preventDefault();var d=b.find(f=>Number(f.getAttribute("data-chip-index"))===this.Aa+1);this.Aa<b.length&&this.Aa++;let e;d==null||(e=
d.children[0])==null||e.focus();return!1}if(c==="ArrowLeft"||c==="ArrowUp")return a.preventDefault(),b=b.find(e=>Number(e.getAttribute("data-chip-index"))===this.Aa-1),this.Aa>1&&this.Aa--,b==null||(d=b.children[0])==null||d.focus(),!1;c==="Tab"&&a.preventDefault();return!1}Ca(a){var b=a.event||void 0;const c=a.qb.el();c.focus();_.vd(c)&&_.Vv(c);a=a.data&&a.data.nonDismissingElements||[];this.setVisible(!this.isVisible(),b,this.oa().firstElementChild,a);b&&(b=_.yf(b))&&b.preventDefault()}reposition(){if(this.isVisible()){var a=
this.getPopup(),b=this.oa(),c=new _.El(this.offsetX,this.offsetY),d=_.Xi(this.data,1),e=_.Xi(this.data,2);d=qTb(d);e=qTb(e);if(b.offsetParent===null&&b.style.position!=="fixed")this.dismiss();else{if(_.z(this.data,7)){var f=_.Gm(b).width;if(_.z(this.data,9)){_.Cm(a,"");var g=_.Gm(a).width;g>f&&(f=g)}_.Cm(a,f)}f=(_.z(this.data,5)?1:0)|(_.z(this.data,6)?4:0);{const h=window.visualViewport;h&&h.scale!==1?(g=_.mTb(this.getPopup()),g=new _.ed(h.pageTop-g.y,h.pageLeft+h.width-g.x,h.pageTop+h.height-g.y,
h.pageLeft-g.x)):g=void 0}_.ww(b,d,a,e,c,void 0,f,void 0,g)}}}isVisible(){return _.Km(this.getPopup())}dismiss(){this.isVisible()&&this.Ba.dismiss(this.popup)}setVisible(a,b,c,d=[]){const e=this.getPopup();var f=a!==this.isVisible();const g=a?"KyPa0e":"wjOG7e";_.Jm(e,a);a&&_.Of(this.root,e)?_.z(this.data,8)||_.uw().appendChild(e):a||_.Of(this.root,e)||this.root.appendChild(e);a&&(_.z(this.data,15)&&_.Ie(this,{service:{focus:_.hr}}).then(h=>{h.service.focus.hU(new _.lo(e))}),this.trigger("YraOve",
{popup:this}),this.reposition());f&&(this.Ta&&this.oa().setAttribute("aria-expanded",a?"true":"false"),a?(this.Pa&&_.Uv([new _.On(this.popup,"show")]),this.Ka||(this.Ka=!0,_.Nf(e,"BUYwVb"),_.Nf(e,g)),this.Ea()?this.Ba.listen(this.popup,(h,k)=>this.onDismiss(d,h,k),[...rTb,4],this.Mc,!0,!1,()=>{this.setVisible(a,b,c,d)},this.getData("bbena").string()||this.root.getAttribute("jsname")):(f=_.z(this.data,10)?sTb:_.z(this.data,11)?tTb:rTb,this.Ba.listen(this.popup,(h,k)=>this.onDismiss(d,h,k),f,this.Mc,
!0))):this.Ba.unlisten(this.popup),this.trigger(g,{triggerElement:c||null,FMb:(b?b.which||b.keyCode:null)===38?!0:!1,rv:b}))}oa(){return this.Ia("oYxtQd").el()}getPopup(){return this.popup}Ua(){return this.Aa}Da(a,b){this.offsetX=a;this.offsetY=b}Ea(){const a=this.getData("bbena"),b=a.string("")||this.root.getAttribute("jsname");return!(!a.Lb()||!b)}Ha(){this.Ea()&&this.Ba.Wa(()=>{this.setVisible(!0)},this.getData("bbena").string()||this.root.getAttribute("jsname"))}};_.xw.prototype.$wa$NjCoec=function(){return this.Ha};
_.xw.prototype.$wa$OOY56c=function(){return this.Ea};_.xw.prototype.$wa$ruNCD=function(){return this.Ua};_.xw.prototype.$wa$pcAkKe=function(){return this.getPopup};_.xw.prototype.$wa$vBAC5=function(){return this.oa};_.xw.prototype.$wa$IYtByb=function(){return this.dismiss};_.xw.prototype.$wa$eO2Zfd=function(){return this.isVisible};_.xw.prototype.$wa$xKqF2c=function(){return this.reposition};_.xw.prototype.$wa$WFrRFb=function(){return this.Ca};_.xw.prototype.$wa$WJWEae=function(){return this.Va};
_.xw.prototype.$wa$uYT2Vb=function(){return this.qk};_.xw.prototype.$wa$k4Iseb=function(){return this.Ub};_.Yr(_.vw,_.xw);var rTb=[1,2,3],sTb=[1,3],tTb=[1,2];
_.u();
_.rnC=_.x("QC6lPe",[_.Xq,_.Hq]);
_.t("QC6lPe");
var jzG=function(a){const b=a.Ia("deRYT").el().getBoundingClientRect().height;a.TU&&b>32&&(a.Ka=!0,hzG(a),izG(a,!1))},kzG=function(a){a.jd(_.xaC,a.Ba.el()).then(b=>{a.Ea=b;a.isInitialized=!0})},lzG=function(a){const b=a.Ta.el();if(a=a.Ha?a.oa:a.TU){const c=a.style.visibility==="visible";b.getBoundingClientRect().height>50?c||(a.style.visibility="visible",_.Uv([new _.On(a,"show")])):c&&(a.style.visibility="hidden",_.Uv([new _.On(a,"hide")]))}},hzG=function(a){var b=a.Ab("F457ec");a=a.Ab("Stv3Z");b=
b.map(e=>e.offsetTop<32?{left:_.fn(e),right:_.fn(e)+e.offsetWidth}:{left:Infinity,right:-1});const c=Math.min(...b.map(e=>e.left)),d=Math.max(...b.map(e=>e.right));b=a.filter(e=>{const f=e.offsetLeft>d||e.offsetLeft+e.offsetWidth<c;return e.offsetTop<32&&f});b.el()&&(b.setData("visible","true"),_.Rm(b.el(),"hidden",!1))},izG=function(a,b){a.Ab("F457ec").each(d=>{const e=d.offsetTop<32,f=d.getAttribute("data-enc")==="1";!e&&f&&(d.tabIndex=b?0:-1,d.setAttribute("data-uti",b?"1":"0"));e?_.Rm(d,"hidden",
!1):_.Rm(d,"hidden",!b)});const c=mzG(a);a=a.Ia("hj0qK").el();c&&_.af(c)&&c.nodeType===1&&a&&_.af(a)&&a.nodeType===1&&(c.setAttribute("tabindex",b?"-1":"0"),c.setAttribute("data-uti",b?"0":"1"),a.setAttribute("tabindex",b?"0":"-1"),a.setAttribute("data-uti",b?"1":"0"))},mzG=function(a){let b;return((b=a.Ab("Stv3Z").filter(c=>_.Te(c,"visible")!==null))==null?void 0:b.el())||null},nzG=function(a,b){return a.Mc&&a.Ca?a.xi.Ia(b):a.Ia(b)},ozG=function(a,b){b=_.cs(a,b.qb,"sUPGue");var c=nzG(a,"vR6K6b");
_.Fc(c.el(),_.fc(b.getData("df").Lb()?_.ol(b.getData("df")):void 0));if(c=_.ol(b.getData("tldf"))){var d=nzG(a,"hmv8e");_.Fc(d.el(),_.fc(c))}d=nzG(a,"W7S8zf");_.yl.enable(d.el(),"ehbKkb",!c);c=_.ol(b.getData("hw"));nzG(a,"NwvD9c").Zb(c);_.oo(nzG(a,"sYUiq"),"data-url",b.getData("url").string());(d=b.getData("lb").string())&&nzG(a,"WSaGDe").Zb(d);var e=nzG(a,"sNxBId");_.yl.enable(e.el(),"ehbKkb",!d);if(d=b.getData("ex").string())e=nzG(a,"EmRWEc"),_.Fc(e.el(),_.fc(d));e=nzG(a,"iWEtMb");_.yl.enable(e.el(),
"ehbKkb",!d);d=!0;if(e=_.ql(b.getData("tae")))_.Rg(b.getData("te"),!0)?(b=b.getData("tl").string(),a.Ea.Ka(c,b)):(b=_.ol(b.getData("au")),a.Ea.Da(b),b||(d=!1));a.Na(e&&d)},pzG=function(a,b){const c=b.qb.el();var d=a.xi.oa().getBoundingClientRect();const e=c.getBoundingClientRect();d=-d.left+e.left+e.width/2;let f;const g=6+((f=c.parentElement)==null?void 0:f.parentElement).getBoundingClientRect().top-e.top;a.xi.Da(d,g);_.yl.Vv(c,"MR2UAc","F8hUzd");b=_.wf(b)||{};b.nonDismissingElements=[c];a.xi.trigger("EOZ57e",
b);_.Tr(a).listenOnce("wjOG7e",()=>{a.Aa&&(_.yl.Vv(a.Aa,"F8hUzd","MR2UAc"),a.Aa=null);a.notify("xLXIyb")});a.Aa=c},qzG=function(a,b){_.yl.Vv(b.el(),"gjoUyf","ehbKkb");a=a.Ia("deRYT").el();b=_.ol(b.getData("lb"));_.yl.Vv(a.querySelector(`[jsname='${"V67aGc"}'][data-lb='${b}']`),"ehbKkb","gjoUyf");_.Ja(a.querySelectorAll(`[jsname='${"F457ec"}'][data-lb='${b}']:not([data-voc='true'])`),c=>{_.yl.Vv(c,"ehbKkb","gjoUyf")})},rzG=function(a,b){b&&a.kc.oa(b+"&expnd=1")},szG=class extends _.Wr{static Sa(){return{service:{kc:_.Vz,
Re:_.Qu}}}constructor(a){super(a.Oa);this.Ma=this.Ea=this.Ba=this.xi=null;this.isInitialized=this.Ha=!1;this.Aa=null;this.Ka=!1;this.Da=this.Ia("KM35l");this.Ta=this.Ia("deRYT");this.TU=this.Ya("Stv3Z").el();this.oa=this.Ya("hj0qK").el();this.Mc=_.ql(this.getData("dsk"));this.Ca=_.Rg(this.getData("dtpe"),!1);this.Gb=_.Rg(this.getData("requery"),!1);this.kc=a.service.kc;this.Pa=_.Rg(this.getData("edv2ui"),!1);this.Re=a.service.Re;this.hb=_.Rg(this.getData("nlm"),!1);this.Mc&&this.hb&&jzG(this);this.Mc&&
this.Ca?(this.popup=this.Ia("V68bde"),this.jd(_.vw,this.popup.el()).then(b=>{this.xi=b;this.Ba=this.xi.Ia("Cd9BGe");kzG(this);this.xi.oa().removeAttribute("role")})):this.Mc?this.isInitialized=!0:(this.dialog=this.Ia("xtVRad"),this.Ba=this.Ia("Cd9BGe"),kzG(this));this.Da.el()&&(lzG(this),this.Ma=new MutationObserver(b=>{b.forEach(()=>{lzG(this)})}),this.Ma.observe(this.Da.el(),{attributes:!0,childList:!0,subtree:!0}));this.Ua=()=>void lzG(this);this.Re.addListener(this.Ua)}Nb(a){const b=a.targetElement.closest(".xpdxpnd").kb();
this.Mc&&b&&b.offsetHeight!==0&&(b.style.maxHeight="");_.yl.Vv(this.Da.el(),"SkSOXb","KAwqid");this.TU&&_.yl.Vv(this.TU,"gjoUyf",this.Pa?"xRjN5b":"ehbKkb");this.TU.style.visibility="hidden";this.oa&&_.yl.Vv(this.oa,"ehbKkb","GpWwbb");_.Vv(a.qb.el());_.Uv([new _.On(this.TU,"hide"),new _.On(this.oa,"show")]);this.Mc&&this.Ka&&izG(this,!0);this.Mc&&b&&(0,_.Un)(()=>{if(b.offsetHeight!==0){const c=b.offsetHeight;b.style.maxHeight=`${c}px`;b.setAttribute("data-mh",String(c))}},300);this.Ha=!0}Mb(a){_.yl.Vv(this.Da.el(),
"KAwqid","SkSOXb");this.TU&&_.yl.Vv(this.TU,this.Pa?"xRjN5b":"ehbKkb","gjoUyf");this.oa&&_.yl.Vv(this.oa,"GpWwbb","ehbKkb");this.oa.style.visibility="hidden";this.Mc&&this.Ka&&izG(this,!1);_.Vv(a.qb.el());_.Uv([new _.On(this.TU,"show"),new _.On(this.oa,"hide")]);this.Ha=!1}Na(a){const b=nzG(this,"Cd9BGe");_.yl.enable(b.el(),"gjoUyf",a);_.yl.enable(b.el(),"ehbKkb",!a)}Cb(){this.Ba&&this.Ba.focus()}Bb(){this.notify("xLXIyb")}Va(a){if(this.isInitialized){var b=1;this.Mc&&!this.Ca&&(b=0);_.Vv(a.qb.el(),
{interactionContext:b});if(_.Rg(a.qb.getData("voc"),!1))qzG(this,a.qb);else if(this.Gb||this.Mc&&!this.Ca)rzG(this,_.cs(this,a.qb,"sUPGue").getData("url").string());else if(this.Mc){if(this.Ca){if(this.Aa){if(this.Aa===a.qb.el()){this.xi.setVisible(!1);return}this.xi.setVisible(!1)}ozG(this,a);pzG(this,a)}}else{ozG(this,a);const c=this.Ia("SFgnYd").el();this.jd(_.Ew,this.dialog.el()).then(d=>{d.oa(c)})}}}Wa(a){_.Vv(a.targetElement.el());rzG(this,a.targetElement.getData("url").string())}wb(){}};
szG.prototype.$wa$Gmtrjd=function(){return this.wb};szG.prototype.$wa$X4aiyd=function(){return this.Wa};szG.prototype.$wa$DAFmqe=function(){return this.Va};szG.prototype.$wa$pnFSEb=function(){return this.Bb};szG.prototype.$wa$yJjTGf=function(){return this.Cb};szG.prototype.$wa$zAge7b=function(){return this.Na};szG.prototype.$wa$NHN6me=function(){return this.Mb};szG.prototype.$wa$Aq3Esf=function(){return this.Nb};_.Yr(_.rnC,szG);
_.u();
});
// Google Inc.
