loaded_h_0(function(_){var window=this;
_.eke={name:"vvv"};
_.Oje=!!(_.xh[31]&1);_.Pje=!!(_.xh[70]&4096);_.Qje=!!(_.xh[88]>>28&1);_.Rje=!!(_.xh[88]>>29&1);_.Sje=!!(_.xh[89]&1);_.Tje=!!(_.xh[89]&2);_.Uje=!!(_.xh[89]&4);_.Vje=!!(_.xh[89]&8);_.Wje=!!(_.xh[89]&256);_.Xje=!!(_.xh[89]&512);_.Yje=!!(_.xh[89]&2048);_.Zje=!!(_.xh[89]&4096);_.$je=!!(_.xh[89]&8192);_.ake=!!(_.xh[89]>>14&1);_.bke=!!(_.xh[89]>>15&1);_.cke=!!(_.xh[89]>>16&1);_.dke=!!(_.xh[89]>>17&1);
var UZc;UZc=function(a){_.zZc.set(a.state,a);a.wrb&&_.GZc.set(a.wrb,a);_.HZc===a.state&&(0,_.re)(()=>{_.JZc(a.state)})};_.VZc=class extends _.Je{constructor({state:a,wrb:b,u9:c,Mga:d,onReady:e,qBb:f}){super();this.oa=[];this.state=a;this.wrb=b;this.u9=c;this.Mga=d;this.onReady=e;this.qBb=f;UZc(this)}Qv(a,b,c,d=0){a=a+"\n"+b;_.vZc[a]={J1c:c,Voc:d};this.oa.push(a)}ud(){_.zZc.delete(this.state);this.wrb&&_.GZc.delete(this.wrb);for(const a of this.oa)delete _.vZc[a]}};
_.t("C8ffD");
var gke,ike,jke,lke,kke,oke,nke;_.fke=function(a){const b=new Map;a.split(",").forEach(c=>{const [d,e]=c.split(":");b.set(d,e)});return b};gke={W_d:_.VZc};ike=async function(a){try{_.y(await _.y(_.hke(a,a.Aa)))}finally{_.y()}};jke=async function(a,b){try{b&&a.Aa&&a.Aa!==b&&(_.y(await _.y(a.oa.promise)).WU(null),a.u9())}finally{_.y()}};lke=function(a,b){return kke(a,b).promise};
kke=function(a,b){let c=a.Ba.get(b);if(a.Ea!==null&&b===a.Ea.getContentId())return b=_.qe(),b.resolve(a.Ea),b;c||(c=_.qe(),a.Ba.set(b,c));return c};oke=function(a,b){if(!a.Ma){var c=b.phd;c||(a.Ma=!0);var d=b.Bib;d?(d.style.display="none",_.zo(b,d),document.body.appendChild(d),_.mke(a,b,d),a.Ha.resolve(d),c&&(a.Ma=!0),a.oa.promise.then(e=>{e.zJe(()=>{nke(a)})})):c||nke(a)}};nke=function(a){a.Pa=!1;for(const b of a.Ba.values())b.promise.then(c=>{c.F7b()})};
_.qke=function(a,b,c=!1){const d=_.fke(b),e=kke(a,d.get("cid")),f=(0,_.Un)(()=>{e.reject()},500);e.promise.then(g=>{(0,_.Vn)(f);a.oa.promise.then(h=>{if(!c){var k=_.fke(_.uf("vld")).get("cid");if(d.get("cid")!==k)return}k=a.Ca(g);g.TRb||g.lGc(!0);h.setContent(g);h.onShow(g.zHc(),g.n6a);h.yrd(k,g.dGb,g.KZa);h.u6a(k,(0,_.pke)(a.Wa==="",a.Aa),g.KZa);k=g.zHc();h=h.e0.getBoundingClientRect().bottom;g.notify("tfBUaf",{triggerEl:k,WYe:h})})}).then(void 0,()=>{a.Da=d.get("cid");_.Wd(Error("fn"));if(_.Uje&&
a.Da&&a.Da.startsWith("SportsLr-")){const g=a.Ac.location.href.split("#")[0];_.rf("",g,!0);a.kc.navigateTo(g,!0)}else _.tf()});return a.Ha.promise};_.hke=async function(a,b){try{window.dispatchEvent(new Event("videoviewerclose"));let c=null;if(b){const d=_.fke(b).get("cid");if(d)try{const e=a.Ba.get(d);if(e){const f=_.y(await _.y(e.promise)),g=f.zHc(!0);f.notify("G2QjU",{triggerEl:g});g&&(_.Se(g,"nprvw",""),g.focus());c=f.n6a}}catch(e){_.y()}}a.Aa=null;a.oa.promise.then(d=>{d.WU(c);d.stop()})}finally{_.y()}};
_.vke=class extends _.bo{static Sa(){return{service:{Ac:_.iv,kc:_.Vz}}}constructor(a,b){super();this.Ka=b;this.Pa=!0;this.Ta=this.Na=this.Ma=!1;this.Ea=null;this.Da=void 0;this.DGd=_.qe();this.Aa=null;this.kBd=_.rke;this.Wa=_.HZc;this.oa=_.qe();this.Ha=_.qe();this.Ac=a.service.Ac;this.kc=a.service.kc;this.Ba=new Map;a=new gke.W_d({state:this.Ka,u9:()=>this.u9(),Mga:()=>{ike(this)}});a.Qv("",this.Ka,this.Va.bind(this),0);a.Qv(this.Ka,"",this.Ua.bind(this),1);_.nf("vld",c=>{jke(this,c)})}Va(){const a=
_.fke(_.uf("vld")),b=_.qe();lke(this,a.get("cid")).then(c=>{this.oa.promise.then(d=>{try{d.e$d(c.DJa,c.m$c).play().then(()=>{_.ske(this.Ha);b.resolve()})}catch(e){b.resolve()}})}).then(void 0,()=>{b.resolve()});return b.promise}Ua(){const a=_.qe();this.oa.promise.then(b=>{const c=b.hed();c?c.play().then(()=>{b.Mcd();_.tke(this.Ha);a.resolve()}):a.resolve()});return a.promise}unregister(a){this.Ba.delete(a.getContentId())}register(a,b,c,d){this.Pa||a.F7b();this.Da===a.getContentId()&&(this.Ba.delete(a.getContentId()),
this.Da=void 0);kke(this,a.getContentId()).resolve(a);oke(this,a);this.Na||!b&&!c||(this.Na=!0,(()=>{this.oa.promise.then(e=>{e.yrd(this.Ca(a),a.dGb,a.KZa)})})());!this.Ta&&c&&(this.Ta=!0,_.uke(()=>{this.oa.promise.then(e=>{d?e.Tkb(this.Ca(a),a.lC,a.KZa):e.u6a(this.Ca(a),a.lC,a.KZa)})}))}u9(){this.Aa=_.uf("vld");return _.qke(this,this.Aa)}};_.uke=function(a){a()};_.ske=function(){};_.tke=function(){};_.pke=function(a,b){return b?(a=_.fke(b).get("st"))?Number(a):0:0};_.mke=function(a,b){a.oa.resolve(b.aOb())};
_.rke=function(){};_.Pe(_.vke);
_.Oje&&(_.pke=function(a,b){if(!b)return 0;var c=_.fke(b).get("st");c=c?Number(c):0;if(a)return c;a=_.ne("l")?_.lf("l",_.eke):null;if(!a)return 0;try{c=Number(a.get(b))||c,a.remove(b)}catch(d){return(b=(new URLSearchParams(this.Ac.location.href)).get("vld"))&&a.remove(b),_.Wd(Error("gn")),0}return c});_.dke&&(_.ske=a=>{const b=document.body.getBoundingClientRect().y-Number(document.body.style.paddingTop.replace("px","")),c=b<0&&!!document.body.style.top;a.promise.then(d=>{d.style.top=c?String(Math.abs(b))+"px":"";d.style.position=c?"absolute":""})},_.tke=a=>{a.promise.then(b=>{b.style.top="";b.style.position=""})});
_.u();
_.wke=_.jr("C8ffD",[_.Gq,_.Xq]);
_.yke=_.x("ZUBru",[_.wke]);
_.t("ZUBru");
_.zke=class extends _.vke{constructor(a){super(a.Oa,"ive")}Ca(a){var b=_.uf("vld");b=_.fke(b);return b.has("vid")?{aspectRatio:a.Zn(),id:b.get("vid"),bMc:a.vna(),DBa:a.DBa}:{aspectRatio:a.Zn(),id:a.iW(),bMc:a.vna(),DBa:a.DBa}}};_.Me(_.yke,_.zke);
_.u();
_.Tke=function(a,b,c,d){a&&b.trim()&&(c.trim()&&_.Vv(a),d?(a=_.ac(b))&&_.Cc(window,a,"_blank"):_.je(b))};
_.Bke=function(a,b){return _.Uf(a,1,b)};_.Cke=function(a,b){return _.Uf(a,2,b)};_.Dke=function(a,b){return _.Uf(a,3,b)};_.Eke=function(a,b){return _.Uf(a,4,b)};_.Fke=function(a,b){return _.Kg(a,5,b)};_.Gke=function(a,b){return _.Kg(a,6,b)};_.Hke=function(a,b){return _.oh(a,8,b)};_.Ike=function(a,b){return _.Uf(a,9,b)};_.Jke=function(a,b){return _.Uf(a,10,b)};_.Kke=function(a,b){return _.Uf(a,11,b)};_.Lke=function(a,b){return _.Jg(a,13,b)};_.Mke=function(a,b){return _.Kg(a,14,b)};
_.Nke=function(a,b){return _.Kg(a,15,b)};_.Oke=function(a,b){return _.Kg(a,16,b)};_.Pke=function(a,b){return _.Uf(a,17,b)};_.Qke=function(a,b){return _.Kg(a,18,b)};_.Rke=function(a){return _.Kg(a,19,_.Fw)};
_.Ske=class extends _.m{constructor(a){super(a)}iW(){return _.A(this,1)}getContentId(){return _.A(this,2)}getVideoUrl(){return _.A(this,3)}Una(){return _.zj(this,3)}iMa(){return _.A(this,4)}QK(){return _.A(this,9)}Tp(){return _.A(this,10)}Dm(){return _.A(this,11)}getTitle(){return _.A(this,12)}setTitle(a){return _.Uf(this,12,a)}ld(){return _.zj(this,12)}Zn(){return _.vi(this,13)}Nv(){return _.xj(this,13)}rP(){return _.Xh(this,13)}vna(){return _.z(this,14)}wF(){return _.z(this,15)}};
_.Ske.prototype.ob="Qklibc";
_.Ake=_.x("rTuANe",[_.yke]);
_.xke=_.x("kKVhdc",[_.wke]);
_.t("rTuANe");
var Xke=function(a){return Array.from(a).map(([b,c])=>b+":"+c).join(",")},Yke=function(a,b,c=0){return{vld:Xke(new Map([["cid",a],["vid",b],["st",String(c)]]))}},Zke=function(a){return a.yBa?"tpive":"ive"},$ke=function(a,b=0){const c=Zke(a);a=Yke(a.contentId,a.videoId,b);_.iZc(c,a)},ble=function(a,b){const c={lC:a.lC,triggerEl:null,type:4,Sh:""};b=ale(a,b,"vll")||ale(a,b,"ved");if(!b)return c;var d=_.Te(b,"ved");if(!b||!d)return c;c.triggerEl=b;c.Sh=d;if((!a.Ba||a.Ca)&&c.triggerEl.hasAttribute("href")&&
c.triggerEl.getAttribute("href")!=="#")return c.type=5,c;if((!a.Ba||a.Ca)&&a.Aha)return c.type=6,c;if(a.Aa)return c.type=3,c;if(b.hasAttribute("href")){var e;d=(e=b.getAttribute("href")||"")==null?void 0:e.startsWith(`#fpstate=${Zke(a)}`)}else d=!1;if(d)return c.type=0,c;if(_.Ve(b,"time"))return a=Number(_.Te(b,"time")),c.type=1,c.lC=a,c;if(!_.Ve(b,"vll"))return c;c.type=2;return c},ale=function(a,b,c){for(;b!==null&&b!==a.oa();){if(_.Ve(b,c))return b;b=_.zf(b)}return null},dG=class extends _.Wr{static Sa(){return{service:{cGb:_.zke},
Ef:{b$:_.Ske}}}constructor(a){super(a.Oa);this.Ba=!0;this.TRb=this.Ca=!1;this.Bib=this.triggerEl=this.KZa=null;var b;let c;this.contentId=(c=(b=a.Ef.b$)==null?void 0:b.getContentId())!=null?c:_.pl(this.getData("cid"),"");let d,e;this.videoId=(e=(d=a.Ef.b$)==null?void 0:d.iW())!=null?e:_.pl(this.getData("vid"),"");let f,g;this.yBa=(g=(f=a.Ef.b$)==null?void 0:f.getVideoUrl())!=null?g:_.pl(this.getData("vurl"),"");let h,k;this.Aa=(k=(h=a.Ef.b$)==null?void 0:h.iMa())!=null?k:_.pl(this.getData("tpvid"),
"");this.zPd=_.pl(this.getData("tpvt"),"");let l,n;this.phd=(n=(l=a.Ef.b$)==null?void 0:_.z(l,5))!=null?n:this.getData("esrvl").Lb();let q,r;this.Da=(r=(q=a.Ef.b$)==null?void 0:_.z(q,6))!=null?r:this.getData("eiv").Lb();let v,B;this.Tkb=(B=(v=a.Ef.b$)==null?void 0:_.z(v,7))!=null?B:this.getData("plv").Lb();let G,M;this.lC=(M=(G=a.Ef.b$)==null?void 0:_.rd(G,8))!=null?M:_.ad(this.getData("vst"),0);let N,T;this.canonicalUrl=(T=(N=a.Ef.b$)==null?void 0:N.QK())!=null?T:_.pl(this.getData("curl"),"");let Z,
Y;this.Aha=(Y=(Z=a.Ef.b$)==null?void 0:Z.Tp())!=null?Y:_.pl(this.getData("surl"),"");let ea,la;this.publisher=(la=(ea=a.Ef.b$)==null?void 0:ea.Dm())!=null?la:_.pl(this.getData("pubr"),"");let oa,ha;this.title=(ha=(oa=a.Ef.b$)==null?void 0:oa.getTitle())!=null?ha:_.pl(this.getData("title"),"");let va,Ca;this.aspectRatio=(Ca=(va=a.Ef.b$)==null?void 0:va.Zn())!=null?Ca:_.ad(this.getData("ar"),1.778);let Ea,ib;this.bMc=(ib=(Ea=a.Ef.b$)==null?void 0:Ea.vna())!=null?ib:this.getData("issv").Lb();let Oa,
zb;this.Mc=(zb=(Oa=a.Ef.b$)==null?void 0:_.z(Oa,19))!=null?zb:this.getData("dsktp").Lb();let lb,wb;this.Ma=(wb=(lb=a.Ef.b$)==null?void 0:lb.wF())!=null?wb:this.getData("va").Lb();let Kb,Ib;this.Nyb=(Ib=(Kb=a.Ef.b$)==null?void 0:_.z(Kb,16))!=null?Ib:this.getData("sport").Lb();let oc,sc;this.DBa=(sc=(oc=a.Ef.b$)==null?void 0:_.A(oc,17))!=null?sc:_.pl(this.getData("eidt"),"");this.cGb=a.service.cGb;this.Ea=_.qe();let Nc,pc;this.Jhb=(pc=(Nc=a.Ef.b$)==null?void 0:_.z(Nc,18))!=null?pc:this.getData("sa").Lb();
this.lGc(!1);this.DJa=this.Ya("zccVWc").el();this.DJa||(this.DJa=this.oa().querySelector("[jsname=zccVWc]"));this.m$c=this.Ya("eaODzd").el();(b=_.cle(this,this.Ka,this.Kc))&&this.Xd(b);this.yBa?_.Uke(_.xke,this.Fn()).then(hd=>{this.Ea.resolve(hd);hd.register(this,this.Da,this.Tkb,!1);this.addOnDisposeCallback(()=>{hd.unregister(this)})}):(a.service.cGb.register(this,this.Da,this.Tkb,!0),this.addOnDisposeCallback(()=>{a.service.cGb.unregister(this)}));_.dle(this);this.Jhb&&(b=Yke(this.contentId,this.videoId,
0),_.pf({fpstate:"ive",vld:b.vld},!0))}lGc(a){try{this.Bib=this.Ya("KG3hVc").el();this.n6a=this.Ia("av05vb").el();this.dGb=this.Ia("faGZad").el().getAttribute("data-ved");this.KZa=this.Ya("r5sc8c").el();const b=this.Ya("RB2wHd").el();this.awd=b?b.getAttribute("data-ved"):null;const c=this.Ya("UqHlMb").el();this.Wcd=c?c.getAttribute("data-ved"):null;const d=this.Mc?this.Ya("jrH4Ac").el():this.Ya("CyezIf").el();this.EDd=d?d.getAttribute("data-ved"):null;this.q1c=this.Ia("WeQmVd").el();this.Owc=this.Ia("KtM8D").el();
this.T4b=this.Ya("JJkIve").el();this.Nmc=this.Ya("N4J2sf").el();this.Ygc=this.Ya("mz5gdb").el();this.NQb=this.Ia("FvylMd").el();this.TRb=this.Ba=!0}catch(b){this.Ba=!1,a&&_.Wd(Error("hn"))}}QK(){return this.canonicalUrl}getContentId(){return this.contentId}iW(){return this.Aa?this.Aa:this.videoId}getVideoUrl(){return this.yBa}iMa(){return this.Aa}rc(){return this.zPd}Gb(){return this.Bib}aOb(){return this.Bib?this.xc(this.Bib,_.wo):_.ng()}Nb(){return this.awd}Va(){return this.Wcd}Rb(){return this.EDd}Cb(){return this.n6a}qc(){return this.q1c}Ua(){return this.Owc}Ta(){return this.T4b}Qb(){return this.Nmc}Mb(){return this.Ygc}Pa(){return this.DJa}Na(){return this.m$c}Bb(){return this.Nyb}Yb(){return this.lC}zHc(a){const b=
this.triggerEl;a&&(this.triggerEl=null);return b}hb(){return this.NQb}yc(){return this.dGb}Vb(){return this.KZa}Tp(){return this.Aha}Dm(){return this.publisher}getTitle(){return this.title}Zn(){return this.aspectRatio}vna(){return this.bMc}Ha(){return this.Jhb}F7b(){this.Ca=!0}oa(){return this.getRoot().el()}zwb(){let a;return((a=this.NQb.querySelector("img"))==null?void 0:a.getAttribute("src"))||""}wF(){return this.Ma}dac(){return!!this.yBa}async cPb(){return this.dac()?this.Ea.promise:this.cGb}kFd(){_.ele(this)}Wa(){return this.phd}Jc(){return this.DBa}Lc(a){if(a.data===
void 0)$ke(this,0);else{var b=0;typeof a.data==="number"?b=a.data:a.data!==void 0&&(b=a.data.videoStartTimeInSeconds,this.triggerEl=a.data.triggerEl);$ke(this,b)}}wb(){return this.TRb}Oc(a){this.TRb||this.lGc(!0);var b=a.event;b=!(!b.shiftKey&&!b.metaKey);var c=a.targetElement.el();c=ble(this,c);var d=c.lC;const e=c.triggerEl,f=c.type;this.triggerEl=e;if(!this.TRb)return _.Tke(e,this.Aha,c.Sh,b),!1;switch(f){case 5:return!0;case 6:return _.Tke(e,this.Aha,c.Sh,b),!1;case 4:case 0:return!0;case 1:case 2:case 3:_.Tje&&
(this.cGb.Ea=this);if(e&&_.fle(this,e,d))return a.event.preventDefault(),!1;this.lC=d;a.event.preventDefault();a=Zke(this);d=Yke(this.contentId,this.yBa?this.Aa:this.videoId,this.lC);if(b)return _.Tke(e,"#fpstate=ive&vld="+d.vld,c.Sh,b),!1;_.iZc(a,d);return!1;default:return!0}}Ka(){_.gle(Zke(this),_.HZc)}Kc(){_.hle(Zke(this),_.HZc)}};dG.prototype.$wa$h5M12e=function(){return this.Oc};dG.prototype.$wa$go7egd=function(){return this.wb};dG.prototype.$wa$NT5WYc=function(){return this.Lc};
dG.prototype.$wa$CtIcLd=function(){return this.Jc};dG.prototype.$wa$E4iai=function(){return this.Wa};dG.prototype.$wa$L3Y2Ob=function(){return this.kFd};dG.prototype.$wa$H8Becc=function(){return this.cPb};dG.prototype.$wa$QQATAe=function(){return this.dac};dG.prototype.$wa$OsMUdb=function(){return this.wF};dG.prototype.$wa$fad1Q=function(){return this.zwb};dG.prototype.$wa$L4rKVc=function(){return this.oa};dG.prototype.$wa$puSBVe=function(){return this.F7b};dG.prototype.$wa$NZacTd=function(){return this.Ha};
dG.prototype.$wa$NZ7GFb=function(){return this.vna};dG.prototype.$wa$KsOwSb=function(){return this.Zn};dG.prototype.$wa$RK67Z=function(){return this.getTitle};dG.prototype.$wa$nBTirb=function(){return this.Dm};dG.prototype.$wa$xMdwee=function(){return this.Tp};dG.prototype.$wa$Ykk09d=function(){return this.Vb};dG.prototype.$wa$qmNVnf=function(){return this.yc};dG.prototype.$wa$W3G5Wd=function(){return this.hb};dG.prototype.$wa$LbIcBe=function(){return this.Yb};dG.prototype.$wa$R3tS9b=function(){return this.Bb};
dG.prototype.$wa$hPvkic=function(){return this.Na};dG.prototype.$wa$MrMul=function(){return this.Pa};dG.prototype.$wa$esRZGe=function(){return this.Mb};dG.prototype.$wa$vRcUmd=function(){return this.Qb};dG.prototype.$wa$Bxr1Hc=function(){return this.Ta};dG.prototype.$wa$j0ArXe=function(){return this.Ua};dG.prototype.$wa$pgXRYb=function(){return this.qc};dG.prototype.$wa$FXJCFb=function(){return this.Cb};dG.prototype.$wa$FYZ96=function(){return this.Rb};dG.prototype.$wa$JUWPAf=function(){return this.Va};
dG.prototype.$wa$FD8qsb=function(){return this.Nb};dG.prototype.$wa$jwm0Z=function(){return this.aOb};dG.prototype.$wa$pNr71d=function(){return this.Gb};dG.prototype.$wa$Iyj6yd=function(){return this.rc};dG.prototype.$wa$bdSK4d=function(){return this.iMa};dG.prototype.$wa$c8mxO=function(){return this.getVideoUrl};dG.prototype.$wa$RAoLoe=function(){return this.iW};dG.prototype.$wa$Ix09yb=function(){return this.getContentId};dG.prototype.$wa$X8QQJc=function(){return this.QK};_.cle=function(){return null};
_.gle=function(){};_.hle=function(){};_.ele=function(){};_.dle=function(){};_.fle=function(){return!1};_.Yr(_.Ake,dG);
if(_.Zje){const a=_.Qb().oa,b=_.Le(_.$n,a),c=_.Le(_.Iq,a);_.cle=(d,e,f)=>{const g=new _.dn(d);b.then(h=>{g.listen(h.get(),"pageshow",e);g.listen(h.get(),"pagehide",f)});return g};_.gle=(d,e)=>{d===e&&c.then(f=>{f.isAvailable()&&f.enterBasicMode(48)})};_.hle=(d,e)=>{d===e&&c.then(f=>{f.isAvailable()&&f.exitBasicMode(48)})}};
_.u();
});
// Google Inc.
