loaded_h_0(function(_){var window=this;
_.AyC=_.x("HWk0Gf",[]);
_.t("HWk0Gf");
var IpJ=function(a){a.Ab("TFTr6").each(b=>{_.Nf(b,"mIm6Ue",b)})},JpJ=class extends _.Wr{constructor(a){super(a.Oa);this.oa=this.Aa=!1;this.Ya("uFwVBb").size()>0&&_.Nf(this.getRoot().el(),"JLw8x",{Pw:this.Ia("uFwVBb").el(),GK:this.Ya("AbEqqc").size()>0?this.Ia("AbEqqc").el():null});IpJ(this);this.OE=this.getRoot().el();this.Da=this.Ya("PrRfmd");this.Ca=this.getRoot().getData("onhoverEnabled").Lb();this.lastIndex=_.ad(this.getRoot().getData("lastIndex"),-1);this.Ca&&(this.OE.addEventListener("mouseleave",
()=>{this.Aa=!1}),a=this.Da.el(),a.addEventListener("mouseenter",()=>{this.oa=!0}),a.addEventListener("mouseleave",()=>{this.oa=!1;this.Ba({data:-1})}))}Ub(){if(this.Ca){this.OE.removeEventListener("mouseleave",()=>{this.Aa=!1});const a=this.Da.el();a.removeEventListener("mouseenter",()=>{this.oa=!0});a.removeEventListener("mouseleave",()=>{this.oa=!1;this.Ba({data:-1})})}super.Ub()}Ba(a){if(this.Ca&&(!this.oa||a.data!==-1)){var b=this.Aa?25:300;this.Aa=!0;_.Nf(this.OE,"JojDRb",{delay:b,index:a.data,
kYf:a.data===this.lastIndex})}}};JpJ.prototype.$wa$wJlvye=function(){return this.Ba};JpJ.prototype.$wa$k4Iseb=function(){return this.Ub};_.Yr(_.AyC,JpJ);
_.u();
_.n8j=_.x("yfZcPd",[]);
_.t("yfZcPd");
var o8j=class extends _.Wr{constructor(a){super(a.Oa);this.OE=this.getRoot().el();this.Da=_.fe(this.OE,"mouseenter",(0,_.Tn)(this.Aa,this));this.Ea=_.fe(this.OE,"mouseleave",(0,_.Tn)(this.oa,this));this.Ba=_.fe(this.OE,"focusin",(0,_.Tn)(this.Ha,this));this.Ca=_.fe(this.OE,"focusout",(0,_.Tn)(this.oa,this))}Ub(){_.bn(this.Da);_.bn(this.Ea);_.bn(this.Ba);_.bn(this.Ca);super.Ub()}Aa(){this.notify("rtcVre");this.notify("cCXahc")}Ha(a){a=a.target;a instanceof HTMLElement&&_.Ve(a,"nprvw")?_.We(a,"nprvw"):
(this.notify("rtcVre"),this.notify("cCXahc"))}oa(){this.notify("hAjFqb");this.notify("SUYuh")}};o8j.prototype.$wa$rxQYoc=function(){return this.oa};o8j.prototype.$wa$pgzxTb=function(){return this.Aa};o8j.prototype.$wa$k4Iseb=function(){return this.Ub};_.Yr(_.n8j,o8j);
_.u();
_.Sy=function(a,b,c){_.Je.call(this);this.jY=c!=null?(0,_.ge)(a,c):a;this.Ea=b;this.Da=(0,_.ge)(this.IVd,this);this.oa=!1;this.Aa=0;this.Ba=this.Sq=null;this.Ca=[]};_.Dh(_.Sy,_.Je);_.aa=_.Sy.prototype;_.aa.fire=function(a){this.Ca=arguments;this.oa=!1;this.Sq?this.Ba=_.Ch()+this.Ea:this.Sq=_.on(this.Da,this.Ea)};_.aa.stop=function(){this.Sq&&(_.pn(this.Sq),this.Sq=null);this.Ba=null;this.oa=!1;this.Ca=[]};_.aa.pause=function(){++this.Aa};
_.aa.resume=function(){this.Aa&&(--this.Aa,!this.Aa&&this.oa&&(this.oa=!1,this.jY.apply(null,this.Ca)))};_.aa.ud=function(){this.stop();_.Sy.xf.ud.call(this)};_.aa.IVd=function(){this.Sq&&(_.pn(this.Sq),this.Sq=null);this.Ba?(this.Sq=_.on(this.Da,this.Ba-_.Ch()),this.Ba=null):this.Aa?this.oa=!0:(this.oa=!1,this.jY.apply(null,this.Ca))};
_.t("Dpem5c");
var XEc,$Ec,ZEc,YEc,bFc,aFc;XEc=class{constructor(a,b){this.oa=a;this.container=b;this.Aa=!1}};$Ec=function(a){if(!a.Ea)if(a.Ca)YEc(a);else if(a.oa.size!==0){var b=a.oa.values().next().value.container.getBoundingClientRect(),c=_.Tl();c=new _.qm(0,0,c.width,c.height);if(Math.abs(a.Da-b.y)>50||!c.contains(b))a.Ca=!0,a.Da=-1,ZEc(a),YEc(a)}};ZEc=function(a){a.oa.forEach(b=>{b.oa.aPa()});a.oa.clear()};YEc=function(a){if(a.Aa.size!==0){var b=aFc(a);a.oa.has(b[0])||(ZEc(a),bFc(a,b))}};
bFc=function(a,b){b.length!==0&&(b.forEach(c=>{a.oa.add(c)}),a.oa.forEach(c=>{c.oa.dYa()}))};aFc=function(a){let b=99999;const c=[];a.Aa.forEach(d=>{var e=d.container.getBoundingClientRect();e.top<0||e.bottom>window.innerHeight||e.height===0||d.Aa||(e=a.Ma-((e.bottom-e.top)/2+e.top),Math.abs(e-b)<10?c.push(d):Math.abs(e)<Math.abs(b)&&(b=e,c.length=0,c.push(d)))});return c};
_.cFc=class extends _.bo{static Sa(){return{service:{},qe:{qF:_.VEc}}}constructor(a){super();this.Ca=!0;this.Da=-1;this.oa=new Set;this.Aa=new Map;this.Ma=window.innerHeight*.35<274?window.innerHeight*.35:274;this.events=new _.dn(this);this.qF=a.qe.qF;this.Ea=!!this.qF.get().Aa();this.qF.listen(b=>{b.Aa()?(this.Ea=!0,ZEc(this)):(this.Ea=!1,$Ec(this))});this.Ka=new _.Sy(()=>{$Ec(this)},50);this.events.listen(window,"scroll",()=>{this.Ka.fire()});document.readyState==="complete"?$Ec(this):_.Zm(_.Ng(),
"load",()=>{$Ec(this)})}Ba(a,b){this.Aa.has(a)||this.Aa.set(a,new XEc(a,b))}Ha(a){a=this.Aa.get(a);a.Aa=!0;this.Ca=!1;this.Da=a.container.getBoundingClientRect().y;this.oa.has(a)||ZEc(this);bFc(this,[a])}};_.Me(_.WEc,_.cFc);
_.u();
_.vje=[0,_.H,-2,_.kk,_.H,-1];
_.uje=_.x("Fy1Pv",[_.WEc]);
_.oje=class extends _.m{constructor(a){super(a)}WN(){return _.wi(this,1)}};_.pje=class extends _.m{constructor(a){super(a)}};_.qje=function(){var a=new _.uPb;return _.iCa(a,3,_.vPb,!0)};_.rje=function(a){var b=new _.uPb;return _.ji(b,2,_.vPb,a)};_.sje=function(a){var b=new _.uPb;return _.ji(b,1,_.vPb,a)};_.tje=function(){const a=new _.jRa;a.start();return a};
_.t("Fy1Pv");
var wje=function(a,b){_.Ve(a,"ved")&&(b=_.Cd(b.Aa(),4),_.Vv(a,{data:{vpp:b}}))},xje=function(a,b){if(a.oa!=null)a.logError("Unable to log preview play start");else{a.oa=Date.now();a.Ba=_.tje();var c=new _.pje;c=_.oh(c,1,a.Aa);c=_.zg(c,2,a.ika);a=_.zg(c,3,a.oa);a=_.sje(a);wje(b,a)}},yje=function(a,b,c){if(a.oa!==null){var d=Date.now(),e=_.qua(a.Ba.elapsedTime()),f=new _.oje;c=_.Ig(f,1,c);d=_.zg(c,2,d);e=_.oh(d,3,e);e=_.rje(e);wje(b,e)}a.reset()},zje=class{constructor(){this.oa=this.Aa=this.ika=null;
this.Ba=new _.jRa}reset(){this.oa=this.Aa=this.ika=null}logError(){}};var Aje={duration:200,easing:"cubic-bezier(.4,0,.2,1)"},Bje={duration:2E3,easing:"cubic-bezier(.4,0,.2,1)"},Cje={duration:500,easing:"cubic-bezier(.4,0,.2,1)"},Dje=function(a){try{a.container=a.Ia(a.containerName).el()}catch(b){(0,_.Un)(()=>{Dje(a)},200);return}a.Yb&&a.Rb.Ba(a,a.getContainer());a.oa=new Eje(a);a.Xd(a.oa);a.Ca=()=>{Fje(a);Gje(a);Hje(a,3)};a.Da=()=>{_.ie().isHidden()?(Fje(a),Hje(a,3)):(Ije(a),a.oa.Aa.reset())};a.Ta=!1;a.trigger("lnkFzb")},Mje=function(a){a.oa&&Jje(a.oa,a.previewMode);
if(!a.Ka){var b=a.oa;Kje(b,a.getData("posterUri"));a.Qb&&b.Mx&&(b.Mx.style.objectFit=a.Vb?"contain":"cover");a.Ka=!0}a.oa.load();a.oa.isReady()&&Lje(a)},Hje=function(a,b){Fje(a);Gje(a);a.oa.pause(b);b=[(new _.qv(a.oa.Mx,Aje)).Fg(.001)];return(new _.tv(b)).play().then(()=>{a.oa.reset()})},Fje=function(a){a.listeners.unlisten(_.Ng(),"pagehide",a.Ca)},Gje=function(a){a.listeners.unlisten(_.ie(),"visibilitychange",a.Da)},Ije=function(a){a.listeners.listen(_.Ng(),"pagehide",a.Ca)},Lje=function(a){return a.oa.play().then(()=>
{if(a.Aa)Hje(a,1);else{xje(a.oa.Aa,a.getContainer());var b=[(new _.qv(a.oa.Mx,Aje)).Fg(1)];_.Ve(a.getContainer(),"ved")&&!a.Ea&&(a.Ea=!0,_.Uv([new _.On(a.getContainer(),"show")]));Ije(a);Nje(a);a.trigger("c3Ckpd",{duration:a.oa.Mx.duration});return(new _.tv(b)).play().then(()=>{a.Aa&&Hje(a,1)})}},b=>{a.handleError(b)})},Nje=function(a){a.listeners.listen(_.ie(),"visibilitychange",a.Da)},cG=class extends _.Wr{static Sa(){return{service:{z9d:_.cFc}}}constructor(a){super(a.Oa);this.container=null;this.Ka=
!1;this.oa=null;this.Aa=this.Ea=!1;this.Da=this.Ca=null;this.Ba=!1;this.Ta=!0;this.Ha=null;this.listeners=new _.dn(this);this.previewMode=3;this.Na=_.pl(this.getData("url"),"");this.Yb=this.getData("rtc").Lb();this.Qb=this.getData("stfc").Lb();this.Vb=this.getData("fci").Lb();this.Nb=this.getData("va").Lb();this.containerName=_.pl(this.getData("co"),"haAclf");this.Rb=a.service.z9d;document.readyState==="complete"?Dje(this):this.Ha=_.Zm(_.Ng(),"load",()=>{Dje(this)})}Cb(){return this.previewMode}hb(){return this.Ba}wb(){return this.Ea}Bb(){return this.oa}getContainer(){return this.container}play(a){if(a=
a.data)this.previewMode=a.VGe===2?2:3;this.dYa()}stop(){this.aPa()}zoom(){try{(0,_.Qn)((new _.qv(this.getContainer(),Bje)).Xn(1.3,1.3,1));const a=this.Ia("GzC2Zd").el();xje(this.oa.Aa,a)}catch(a){this.handleError(a)}}qc(){try{(0,_.Qn)((new _.qv(this.getContainer(),Cje)).Xn(1,1,1));const a=this.Ia("GzC2Zd").el();yje(this.oa.Aa,a,2)}catch(a){this.handleError(a)}}dYa(){this.trigger("cCXahc");if(!(this.Ta||this.Ba||this.Na===""||window.matchMedia("(prefers-reduced-motion: reduce)").matches)){var a=this.getContainer();
const b=_.Tl();(new _.qm(-5,-5,b.width+10,b.height+10)).contains(a.getBoundingClientRect())?this.isPlaying()||(this.Aa=!1,Mje(this)):this.aPa()}}aPa(){this.trigger("SUYuh");this.Aa=!0;this.isPlaying()&&(Hje(this,1),this.Aa=!0,this.Nb&&this.trigger("UOhZB"))}Ua(){this.trigger("Yor6Sc",{duration:this.oa.Mx.duration})}Ma(){this.oa&&!this.oa.isPlaying()&&(this.Aa||Lje(this))}Mb(){return Lje(this)}Va(){this.trigger("UOhZB")}Pa(){Mje(this)}Wa(){Nje(this)}isPlaying(){return this.oa.isPlaying()}Gb(){return this.isPlaying()}isPaused(){return this.oa.isPaused()}handleError(a){if(a&&
(a.name!=="AbortError"||!this.isPaused())){if(a.name==="NotAllowedError"||a.name==="AbortError"){a=this.getContainer();const b=_.qje();wje(a,b)}this.Ba=!0;this.listeners.removeAll();Hje(this,4)}}Ub(){Fje(this);Gje(this);this.Ha!=null&&_.bn(this.Ha);super.Ub()}};cG.prototype.$wa$k4Iseb=function(){return this.Ub};cG.prototype.$wa$lSuz7d=function(){return this.isPaused};cG.prototype.$wa$fQV4Od=function(){return this.Gb};cG.prototype.$wa$nuM91e=function(){return this.isPlaying};
cG.prototype.$wa$hoE5Od=function(){return this.Wa};cG.prototype.$wa$casA0c=function(){return this.Pa};cG.prototype.$wa$vpkr4c=function(){return this.Va};cG.prototype.$wa$sw8RG=function(){return this.Mb};cG.prototype.$wa$ARH9bb=function(){return this.Ma};cG.prototype.$wa$G4CZhb=function(){return this.Ua};cG.prototype.$wa$ja59ec=function(){return this.aPa};cG.prototype.$wa$u7qJ8e=function(){return this.dYa};cG.prototype.$wa$qaCiYe=function(){return this.qc};cG.prototype.$wa$nJjxad=function(){return this.zoom};
cG.prototype.$wa$QKiGd=function(){return this.stop};cG.prototype.$wa$NziyQe=function(){return this.play};cG.prototype.$wa$MxZ2Se=function(){return this.getContainer};cG.prototype.$wa$xfZxVe=function(){return this.Bb};cG.prototype.$wa$IAmvMb=function(){return this.wb};cG.prototype.$wa$vVPI5b=function(){return this.hb};cG.prototype.$wa$DpMiYc=function(){return this.Cb};_.Yr(_.uje,cG);
var Kje=function(a,b){if(a.Mx==null){var c=_.Yl("VIDEO");c.src=_.Zb(_.ac(a.oa.Na)||_.mja);_.yl.add(c,"DqfBw");c.preload="none";a.Mx=c;c.muted=!0;c.setAttribute("autoplay","");c.setAttribute("muted","");c.setAttribute("playsinline","");c.setAttribute("tabindex","-1");c.setAttribute("webkit-playsinline","");b.Lb()&&(c.poster=_.ll(b));c.onloadedmetadata=()=>{a.oa.Ua()};c.onloadeddata=()=>{var d=a.Aa;d.ika===null||d.Aa!=null?d.logError("Unable to log preview load end"):d.Aa=_.qua(d.Ba.elapsedTime());
a.oa.Ma()};a.errorHandler.listen(c,"error",d=>{let e;a.Mx.error?e=Error("dn`"+a.Mx.error.code):e=d.error||d.jg.error;e||(e=Error("en"));a.oa.handleError(e)});Jje(a,a.oa.previewMode);_.bm(a.oa.getContainer());_.dHa(a.oa.getContainer(),c)}},Jje=function(a,b){a.Mx&&(b===3?(a.Mx.loop=!0,a.Mx.onended=null):(a.Mx.removeAttribute("loop"),a.Mx.onended=()=>{a.oa.Va();return Hje(a.oa,2)}))},Eje=class extends _.Je{constructor(a){super();this.Ca=this.Wn=this.Da=this.Ba=!1;this.Mx=null;this.oa=a;this.Aa=new zje;
this.errorHandler=new _.dn(this)}load(){if(!this.Wn){this.Wn=!0;var a=this.Aa;a.ika!=null||a.Aa!=null||a.oa!=null?a.logError("Unable to log preview load start"):(a.ika=Date.now(),a.Ba=_.tje())}this.loaded()||(this.Da=!0,this.Mx.load())}isReady(){let a;return((a=this.Mx)==null?void 0:a.readyState)===HTMLMediaElement.HAVE_ENOUGH_DATA}play(){this.Wn=!1;this.Ba=!0;this.Ca=!1;return new _.Df((a,b)=>{const c=this.Mx.play();c!=null?c.then(a).catch(b):a()})}pause(a){this.Ba&&(this.Ba=!1,this.Ca=!0,yje(this.Aa,
this.oa.getContainer(),a),this.Mx.pause())}reset(){this.Mx.readyState!==HTMLMediaElement.HAVE_NOTHING&&(this.Mx.currentTime=0)}isPlaying(){return this.Ba}isPaused(){return this.Ca}loaded(){return this.Da}ud(){this.errorHandler.dispose();super.ud()}};

_.u();
});
// Google Inc.
